// @generated
#ifndef MOCHI_RENDERER_MATERIALS_H_
#define MOCHI_RENDERER_MATERIALS_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t MOCHI_RENDERER_MATERIALS_DISTORTION_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_FLATLITOPAQUE_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_FLATLITSEETHROUGH_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_GROUNDSHADOW_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_HIGHLIGHTCOMPOSITE_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_LITOPAQUE_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_LITSEETHROUGH_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_LITVERTEXCOLOR_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_OUTLINE_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_UNLITSEETHROUGH_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_UNLITVERTEXCOLOR_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_WIREFRAME_PACKAGE[];
    extern const uint8_t MOCHI_RENDERER_MATERIALS_WIREFRAMEDEPTH_PACKAGE[];
}

#define MOCHI_RENDERER_MATERIALS_DISTORTION_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_DISTORTION_SIZE 71485
#define MOCHI_RENDERER_MATERIALS_DISTORTION_DATA (MOCHI_RENDERER_MATERIALS_DISTORTION_PACKAGE + MOCHI_RENDERER_MATERIALS_DISTORTION_OFFSET)

#define MOCHI_RENDERER_MATERIALS_FLATLITOPAQUE_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_FLATLITOPAQUE_SIZE 940046
#define MOCHI_RENDERER_MATERIALS_FLATLITOPAQUE_DATA (MOCHI_RENDERER_MATERIALS_FLATLITOPAQUE_PACKAGE + MOCHI_RENDERER_MATERIALS_FLATLITOPAQUE_OFFSET)

#define MOCHI_RENDERER_MATERIALS_FLATLITSEETHROUGH_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_FLATLITSEETHROUGH_SIZE 788572
#define MOCHI_RENDERER_MATERIALS_FLATLITSEETHROUGH_DATA (MOCHI_RENDERER_MATERIALS_FLATLITSEETHROUGH_PACKAGE + MOCHI_RENDERER_MATERIALS_FLATLITSEETHROUGH_OFFSET)

#define MOCHI_RENDERER_MATERIALS_GROUNDSHADOW_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_GROUNDSHADOW_SIZE 242122
#define MOCHI_RENDERER_MATERIALS_GROUNDSHADOW_DATA (MOCHI_RENDERER_MATERIALS_GROUNDSHADOW_PACKAGE + MOCHI_RENDERER_MATERIALS_GROUNDSHADOW_OFFSET)

#define MOCHI_RENDERER_MATERIALS_HIGHLIGHTCOMPOSITE_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_HIGHLIGHTCOMPOSITE_SIZE 66861
#define MOCHI_RENDERER_MATERIALS_HIGHLIGHTCOMPOSITE_DATA (MOCHI_RENDERER_MATERIALS_HIGHLIGHTCOMPOSITE_PACKAGE + MOCHI_RENDERER_MATERIALS_HIGHLIGHTCOMPOSITE_OFFSET)

#define MOCHI_RENDERER_MATERIALS_LITOPAQUE_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_LITOPAQUE_SIZE 925128
#define MOCHI_RENDERER_MATERIALS_LITOPAQUE_DATA (MOCHI_RENDERER_MATERIALS_LITOPAQUE_PACKAGE + MOCHI_RENDERER_MATERIALS_LITOPAQUE_OFFSET)

#define MOCHI_RENDERER_MATERIALS_LITSEETHROUGH_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_LITSEETHROUGH_SIZE 760682
#define MOCHI_RENDERER_MATERIALS_LITSEETHROUGH_DATA (MOCHI_RENDERER_MATERIALS_LITSEETHROUGH_PACKAGE + MOCHI_RENDERER_MATERIALS_LITSEETHROUGH_OFFSET)

#define MOCHI_RENDERER_MATERIALS_LITVERTEXCOLOR_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_LITVERTEXCOLOR_SIZE 622787
#define MOCHI_RENDERER_MATERIALS_LITVERTEXCOLOR_DATA (MOCHI_RENDERER_MATERIALS_LITVERTEXCOLOR_PACKAGE + MOCHI_RENDERER_MATERIALS_LITVERTEXCOLOR_OFFSET)

#define MOCHI_RENDERER_MATERIALS_OUTLINE_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_OUTLINE_SIZE 81854
#define MOCHI_RENDERER_MATERIALS_OUTLINE_DATA (MOCHI_RENDERER_MATERIALS_OUTLINE_PACKAGE + MOCHI_RENDERER_MATERIALS_OUTLINE_OFFSET)

#define MOCHI_RENDERER_MATERIALS_UNLITSEETHROUGH_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_UNLITSEETHROUGH_SIZE 63611
#define MOCHI_RENDERER_MATERIALS_UNLITSEETHROUGH_DATA (MOCHI_RENDERER_MATERIALS_UNLITSEETHROUGH_PACKAGE + MOCHI_RENDERER_MATERIALS_UNLITSEETHROUGH_OFFSET)

#define MOCHI_RENDERER_MATERIALS_UNLITVERTEXCOLOR_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_UNLITVERTEXCOLOR_SIZE 63426
#define MOCHI_RENDERER_MATERIALS_UNLITVERTEXCOLOR_DATA (MOCHI_RENDERER_MATERIALS_UNLITVERTEXCOLOR_PACKAGE + MOCHI_RENDERER_MATERIALS_UNLITVERTEXCOLOR_OFFSET)

#define MOCHI_RENDERER_MATERIALS_WIREFRAME_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_WIREFRAME_SIZE 53676
#define MOCHI_RENDERER_MATERIALS_WIREFRAME_DATA (MOCHI_RENDERER_MATERIALS_WIREFRAME_PACKAGE + MOCHI_RENDERER_MATERIALS_WIREFRAME_OFFSET)

#define MOCHI_RENDERER_MATERIALS_WIREFRAMEDEPTH_OFFSET 0
#define MOCHI_RENDERER_MATERIALS_WIREFRAMEDEPTH_SIZE 62407
#define MOCHI_RENDERER_MATERIALS_WIREFRAMEDEPTH_DATA (MOCHI_RENDERER_MATERIALS_WIREFRAMEDEPTH_PACKAGE + MOCHI_RENDERER_MATERIALS_WIREFRAMEDEPTH_OFFSET)

#endif
