# This file was @generated by mochi_gen_py. Do not modify this file by hand!!
#
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pyre-strict

from typing import Any, Callable, Iterator, Optional, Sequence, overload
import numpy as np
import numpy.typing as npt
import mochi_physics

########################################################################################

class BackPropagationSolverParams:
    """Parameters of the solve in differentiability back-propagation."""
    verbosity: mochi_physics.VerbosityLevel
    """Verbosity level of the back-propagation solver's logging."""
    use_newton_outer_solver: bool
    """Use a Newton solver for the outer adjoint solve instead of the default Krylov
    solver.
    """
    outer_solver_max_iter: int
    """Maximum number of outer-solver iterations for the adjoint solve."""
    outer_solver_abs_tol: float
    """Absolute convergence tolerance for the outer solver."""
    outer_solver_rel_tol: float
    """Relative convergence tolerance for the outer solver."""
    outer_solver_convergence_mode: mochi_physics.NonLinearSolverConvergenceMode
    """Convergence-checking mode for the outer solver."""
    inner_solver_abs_tol: float
    """Absolute convergence tolerance for the inner (linear) solver."""
    eps_finite_diff: float
    """Finite-difference step size used for Hessian-vector products in the adjoint
    solve.
    """
    validate_finite_diff: bool
    """Validate analytic Hessian-vector products against finite differences
    (diagnostic; slower).
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        verbosity: mochi_physics.VerbosityLevel | int = ...,
        use_newton_outer_solver: bool = ...,
        outer_solver_max_iter: int = ...,
        outer_solver_abs_tol: float = ...,
        outer_solver_rel_tol: float = ...,
        outer_solver_convergence_mode: mochi_physics.NonLinearSolverConvergenceMode | int = ...,
        inner_solver_abs_tol: float = ...,
        eps_finite_diff: float = ...,
        validate_finite_diff: bool = ...,
    ) -> None: ...

class BackPropagationSceneStats:
    """Performance metrics for the last back-propagation step."""
    total_duration_sec: float
    """Total wall-clock time spent in the last back-propagation step."""
    solve_duration_sec: float
    """Wall-clock time spent in the adjoint solve of the last back-propagation step."""
    max_outer_iters: int
    """Maximum number of outer-solver iterations across all islands in the last
    back-propagation step.
    """
    residual_norm: float
    """Final residual norm of the adjoint solve in the last back-propagation step."""
    finite_diff_valid: bool
    """True if every finite-difference Hvp validation check across every island and
    every Hvp evaluation in this back-prop step passed its tolerance.

    Note:
        Only meaningful when
        :attr:`~superdex.physics.diffsim.BackPropagationSolverParams.validate_finite_diff`
        is set; otherwise stays at its default of true.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        total_duration_sec: float = ...,
        solve_duration_sec: float = ...,
        max_outer_iters: int = ...,
        residual_norm: float = ...,
        finite_diff_valid: bool = ...,
    ) -> None: ...

def make_scene_differentiable(scene: mochi_physics.Scene) -> None:
    """Make a scene differentiable.

    For accuracy reasons, differentiability is only recommended in double precision.
    Differentiability is only supported for rigid and articulated actors, and
    requires :attr:`~superdex.physics.SolverParams.integration_method` to be
    :class:`BACKWARD_EULER <superdex.physics.IntegrationMethod>`. It adds internal
    data to support the invocation of the functions
    :func:`~superdex.physics.diffsim.back_propagate` and
    :func:`~superdex.physics.diffsim.get_step_jacobian`. It also calls
    :func:`~superdex.physics.experimental.apply_improved_convergence_settings`, and
    it logs warnings when overriding non-default scene or actor settings selected by
    the user. Consider changing those settings to retain the same simulation
    behavior if the scene is used elsewhere.

    Args:
        scene (Scene): The scene to make differentiable.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_back_propagation_solver_params(
    scene: mochi_physics.Scene,
) -> BackPropagationSolverParams:
    """Get solver parameters.

    Args:
        scene (Scene): The differentiable scene.

    Returns:
        The back-propagation solver parameters.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_back_propagation_solver_params(
    scene: mochi_physics.Scene,
    params: BackPropagationSolverParams,
) -> None:
    """Set solver parameters.

    Args:
        scene (Scene): The differentiable scene.
        params (BackPropagationSolverParams): The back-propagation solver parameters
            to set.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_back_propagation_scene_stats(
    scene: mochi_physics.Scene,
) -> BackPropagationSceneStats:
    """Get the performance metrics of the last back-propagation step.

    Args:
        scene (Scene): The differentiable scene.

    Returns:
        The performance metrics of the last back-propagation step.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def reset_back_propagation(scene: mochi_physics.Scene) -> None:
    """Reset back-propagation state.

    Must be called once before a backward pass.

    Args:
        scene (Scene): The differentiable scene.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def prepare_back_propagate(
    scene: mochi_physics.Scene,
    state_new: mochi_physics.StateHandle,
    state_old: mochi_physics.StateHandle,
) -> None:
    """Prepare one simulation step for backward mode differentiation.

    Validates the state pair and marks the scene as ready for per-step output
    backward functions and :func:`~superdex.physics.diffsim.back_propagate`. Must be
    called before accumulating per-step loss gradients with output backward
    functions.

    Args:
        scene (Scene): The differentiable scene.
        state_new (StateHandle): State handle at step k (q_k).
        state_old (StateHandle): State handle at step k-1 (q_{k-1}).

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def back_propagate(scene: mochi_physics.Scene) -> None:
    """Backward mode differentiation through the step function.

    Solves the adjoint system to propagate gradients backward through one simulation
    step. Per-step loss gradients should be accumulated into per-actor adjoint
    components after calling
    :func:`~superdex.physics.diffsim.prepare_back_propagate` and before calling this
    function, using output backward functions (e.g.,
    :func:`~superdex.physics.diffsim.get_center_of_mass_transform_backward`,
    :func:`~superdex.physics.diffsim.get_articulated_pose_backward`). The internal
    adjoint buffers are managed by the scene and must be initialized via
    :func:`~superdex.physics.diffsim.reset_back_propagation` before the first call.
    Each call to this function must be preceded by
    :func:`~superdex.physics.diffsim.prepare_back_propagate` for the same state
    pair. Per-actor gradients wrt control inputs and initial conditions can be
    extracted via the corresponding backward functions (e.g.,
    :func:`~superdex.physics.diffsim.set_articulated_target_pose_backward`,
    :func:`~superdex.physics.diffsim.set_center_of_mass_transform_backward`) after
    each BackPropagate call. This function assumes that the forward simulation is
    executed per step by setting inputs, running the step, and reading outputs. The
    state handles must be captured right before and after stepping the simulation
    forward, without setting any inputs in between.

    Args:
        scene (Scene): The differentiable scene.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        TODO: The function is not tested with variable time-stepping yet.
    """

def get_step_jacobian(
    scene: mochi_physics.Scene,
    state_new: mochi_physics.StateHandle,
    state_curr: mochi_physics.StateHandle,
    state_old: mochi_physics.StateHandle,
    out_jac_curr: mochi_physics.ArrayLikeReal,
    out_jac_old: mochi_physics.ArrayLikeReal,
) -> None:
    """Forward mode differentiation through the step function.

    Provides the full column-major Jacobian matrices with the following sizes:
    outJacCurr = dq_t/dq_t-1 (|q| x |q|) and outJacOld = dq_t/dq_t-2 (|q| x |q|).
    The rows and columns of the Jacobian matrices are sorted according to the order
    given in Scene.GetActors(). The input states are three consecutive states
    captured during a simulated trajectory: stateNew = state_t, stateCurr =
    state_t-1, stateOld = state_t-2.

    Args:
        scene (Scene): The differentiable scene.
        state_new (StateHandle): State handle at step t.
        state_curr (StateHandle): State handle at step t-1.
        state_old (StateHandle): State handle at step t-2.
        out_jac_curr (ArrayLikeReal): Jacobian dq_t/dq_t-1, column-major, sized |q|
            x |q|.
        out_jac_old (ArrayLikeReal): Jacobian dq_t/dq_t-2, column-major, sized |q| x
            |q|.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def convert_rigid_gradient_lie_to_rotation_vector(
    state: mochi_physics.TransformRT,
    out_grad: mochi_physics.ArrayLikeReal,
) -> None:
    """Convert in-place gradient wrt rigid-actor state from local (Lie-parameterized)
    representation to full rotation-vector representation.

    This conversion is necessary for gradient-based optimization. outGrad must have
    size 6 (3 translation + 3 rotation DoFs).

    Args:
        state (TransformRT): The rigid-actor state transform.
        out_grad (ArrayLikeReal): In: Lie-parameterized gradient. Out:
            rotation-vector gradient. Size 6.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def convert_rigid_gradient_lie_to_quaternion(
    state: mochi_physics.TransformRT,
    in_grad: mochi_physics.ArrayLikeReal,
    out_grad: mochi_physics.ArrayLikeReal,
) -> None:
    """Convert gradient wrt rigid-actor state from local (Lie-parameterized) to
    quaternion representation.

    This conversion is necessary for gradient-based optimization. inGrad must have
    size 6 (3 translation + 3 rotation DoFs). outGrad must have size 7 (3
    translation + 4 rotation DoFs).

    Args:
        state (TransformRT): The rigid-actor state transform.
        in_grad (ArrayLikeReal): Lie-parameterized gradient. Size 6.
        out_grad (ArrayLikeReal): Quaternion-parameterized gradient. Size 7.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def convert_articulated_gradient_lie_to_rotation_vector(
    actor: mochi_physics.Actor,
    pose: mochi_physics.ArrayLikeReal,
    out_grad: mochi_physics.ArrayLikeReal,
) -> None:
    """Convert in-place gradient wrt articulated-actor pose from local
    (Lie-parameterized) representation to full rotation-vector representation.

    The conversion is applied only to joints with 3D rotations. This conversion is
    necessary for gradient-based optimization. outGrad must have size equal to the
    number of DoFs of the articulated actor.

    Args:
        actor (Actor): The articulated actor.
        pose (ArrayLikeReal): The articulated-actor pose.
        out_grad (ArrayLikeReal): In: Lie-parameterized gradient. Out:
            rotation-vector gradient.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def convert_rigid_gradient_quaternion_to_lie(
    state: mochi_physics.TransformRT,
    in_grad: mochi_physics.ArrayLikeReal,
    out_grad: mochi_physics.ArrayLikeReal,
) -> None:
    """Convert gradient wrt rigid-actor state from quaternion to local
    (Lie-parameterized) representation.

    This conversion is necessary for gradient-based optimization. inGrad must have
    size 7 (3 translation + 4 rotation DoFs). outGrad must have size 6 (3
    translation + 3 rotation DoFs).

    Args:
        state (TransformRT): The rigid-actor state transform.
        in_grad (ArrayLikeReal): Quaternion-parameterized gradient. Size 7.
        out_grad (ArrayLikeReal): Lie-parameterized gradient. Size 6.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def convert_articulated_gradient_rotation_vector_to_lie(
    actor: mochi_physics.Actor,
    pose: mochi_physics.ArrayLikeReal,
    out_grad: mochi_physics.ArrayLikeReal,
) -> None:
    """Convert in-place gradient wrt articulated-actor pose from full rotation-vector
    representation to local (Lie-parameterized) representation.

    The conversion is applied only to joints with 3D rotations. This conversion is
    necessary for gradient-based optimization. outGrad must have size equal to the
    number of DoFs of the articulated actor.

    Args:
        actor (Actor): The articulated actor.
        pose (ArrayLikeReal): The articulated-actor pose.
        out_grad (ArrayLikeReal): In: rotation-vector gradient. Out:
            Lie-parameterized gradient.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_center_of_mass_transform_backward(
    actor: mochi_physics.Actor,
    grad_output: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.get_center_of_mass_transform`.

    Converts the gradient w.r.t. the center-of-mass transform output (translation +
    quaternion) to a Lie-parameterized state gradient and accumulates it into the
    actor. Only rigid actors are supported (standalone or links). Must be called
    before :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The rigid actor (standalone or link).
        grad_output (ArrayLikeReal): Gradient w.r.t. center-of-mass transform output
            (3 translation + 4 quaternion XYZW). Must be of size 7.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_root_transform_backward(
    actor: mochi_physics.Actor,
    grad_output: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.get_root_transform`.

    Converts the gradient w.r.t. the root transform output (translation +
    quaternion) to a Lie-parameterized state gradient and accumulates it into the
    actor. Only rigid actors are supported (standalone or links). Must be called
    before :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The rigid actor (standalone or link).
        grad_output (ArrayLikeReal): Gradient w.r.t. root transform output (3
            translation + 4 quaternion XYZW). Must be of size 7.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_contact_force_world_backward(
    actor: mochi_physics.Actor,
    grad_output: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.get_contact_force_world`.

    Accumulates the gradient w.r.t. the world-frame total contact force into
    prepared per-contact force adjoints. Only rigid actors are supported. Must be
    called after :func:`~superdex.physics.diffsim.prepare_back_propagate` and before
    :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The rigid actor.
        grad_output (ArrayLikeReal): Gradient w.r.t. the total contact force [N] in
            world frame. Must be of size 3.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_contact_force_from_actor_world_backward(
    actor: mochi_physics.Actor,
    other: mochi_physics.Actor,
    grad_output: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for
    :meth:`~superdex.physics.Actor.get_contact_force_from_actor_world`.

    Accumulates the gradient w.r.t. the world-frame contact force from another actor
    into prepared per-contact force adjoints. Only rigid actors are supported. Must
    be called after :func:`~superdex.physics.diffsim.prepare_back_propagate` and
    before :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The rigid actor receiving the contact force.
        other (Actor): The actor exerting the contact force.
        grad_output (ArrayLikeReal): Gradient w.r.t. the contact force [N] in world
            frame. Must be of size 3.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def get_articulated_pose_backward(
    actor: mochi_physics.Actor,
    grad_output: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.get_articulated_pose`.

    Converts the gradient w.r.t. the articulated pose output (joint DOFs in
    rotation-vector representation) to a Lie-parameterized state gradient and
    accumulates it into the actor. Only articulated actors are supported. Must be
    called before :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The articulated actor.
        grad_output (ArrayLikeReal): Gradient w.r.t. articulated pose output. Must
            be of size :meth:`~superdex.physics.Actor.get_num_dofs`.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_articulated_target_pose_backward(
    actor: mochi_physics.Actor,
    out_grad_target_pose: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.set_articulated_target_pose`.

    Reads the accumulated gradients wrt current and previous pose-controller targets
    (dg/dgamma_k and dg/dgamma_{k-1}) and sums them into a single output gradient
    wrt the target pose. Must be called after
    :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The articulated actor with a pose controller.
        out_grad_target_pose (ArrayLikeReal): Gradient wrt target pose (dg/dgamma_k
            + dg/dgamma_{k-1}). Must be of size
            :meth:`~superdex.physics.Actor.get_num_dofs`. The caller is responsible
            for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_articulated_pose_from_joints_backward(
    actor: mochi_physics.Actor,
    out_grad_pose: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for
    :meth:`~superdex.physics.Actor.set_articulated_pose_from_joints`.

    :meth:`~superdex.physics.Actor.set_articulated_pose_from_joints` sets the body
    pose AND initializes the controller targets (both current and previous). This
    dual sums the gradient contributions from all three paths: state, current
    target, and previous target. Must be called after
    :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The articulated actor.
        out_grad_pose (ArrayLikeReal): Gradient wrt the joint pose. Must be of size
            :meth:`~superdex.physics.Actor.get_num_dofs`. The caller is responsible
            for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_articulated_target_velocity_backward(
    actor: mochi_physics.Actor,
    out_grad_target_velocity: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for
    :meth:`~superdex.physics.Actor.set_articulated_target_velocity`.

    The target velocity is applied by computing the previous controller target as
    target_old = target_current - dt * velocity. Therefore, the gradient wrt
    velocity is -dt * dg/dgamma_{k-1}, where dg/dgamma_{k-1} is the gradient wrt the
    previous controller target. Must be called after
    :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The articulated actor with a pose controller.
        out_grad_target_velocity (ArrayLikeReal): Gradient wrt target velocity. Must
            be of size :meth:`~superdex.physics.Actor.get_num_dofs`. The caller is
            responsible for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_articulated_joint_velocities_backward(
    actor: mochi_physics.Actor,
    out_grad_velocities: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for
    :meth:`~superdex.physics.Actor.set_articulated_joint_velocities`.

    :meth:`~superdex.physics.Actor.set_articulated_joint_velocities` sets the joint
    velocities v of an articulated actor. The velocity determines the derived step
    dx = v * dt. Therefore: dL/dv = dt * dL/d(dx) * d(dx)/dq. Additionally, if a
    pose controller is present, it also sets the target velocity which determines
    the previous controller target; therefore it receives a gradient contribution
    from the old controller target. Must be called after
    :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The articulated actor.
        out_grad_velocities (ArrayLikeReal): Gradient wrt joint velocities. Must be
            of size :meth:`~superdex.physics.Actor.get_num_dofs`. The caller is
            responsible for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_external_forces_on_dofs_backward(
    actor: mochi_physics.Actor,
    dof_indices: mochi_physics.ArrayLikeInt,
    out_grad_force_values: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.set_external_forces_on_dofs`.

    Reads the accumulated force gradient at the specified DOF indices. Only
    articulated and standalone rigid actors are supported (not rigid links). Must be
    called after :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The articulated or standalone rigid actor.
        dof_indices (ArrayLikeInt): DOF indices matching the forward call. Must be
            unique and match the size of outGradForceValues.
        out_grad_force_values (ArrayLikeReal): Gradient wrt force values. The caller
            is responsible for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_velocity_backward(
    actor: mochi_physics.Actor,
    out_grad_linear_vel: mochi_physics.ArrayLikeReal,
    out_grad_angular_vel: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.set_velocity`.

    :meth:`~superdex.physics.Actor.set_velocity` sets the rigid-body velocity v =
    (v_com, omega). The velocity determines the derived step dx = v * dt. Therefore:
    dL/dv = dt * dL/d(dx), where dL/d(dx) is the derived-state adjoint. Only
    standalone rigid actors are supported (not articulated links, not soft actors).
    Must be called after :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The rigid actor.
        out_grad_linear_vel (ArrayLikeReal): Gradient wrt linear velocity. Must be
            of size 3. The caller is responsible for accumulation.
        out_grad_angular_vel (ArrayLikeReal): Gradient wrt angular velocity. Must be
            of size 3. The caller is responsible for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def set_center_of_mass_transform_backward(
    actor: mochi_physics.Actor,
    out_grad_transform: mochi_physics.ArrayLikeReal,
) -> None:
    """Backward pass for :meth:`~superdex.physics.Actor.set_center_of_mass_transform`.

    :meth:`~superdex.physics.Actor.set_center_of_mass_transform` directly sets the
    rigid-body state (pose), so this function reads the gradient dL/d(state). The
    output is in quaternion representation (7 elements: translation(3) +
    quaternion(4)), matching the forward API. Only standalone rigid actors are
    supported. Must be called after
    :func:`~superdex.physics.diffsim.back_propagate`.

    Args:
        actor (Actor): The rigid actor.
        out_grad_transform (ArrayLikeReal): Gradient wrt the CoM transform. Must be
            of size 7 (translation(3) + quaternion_XYZW(4)). The caller is
            responsible for accumulation.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """
