/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "mochi_ecs.h"

#include <mochi_core/utils/dynamic_array.h>
#include <mochi_core/utils/error.h>
#include <mochi_core/utils/reflection.h>
#include <mochi_core/utils/span.h>
#include <mochi_physics/utils/mochi_physics_macros.h>

#include <cstdint>
#include <functional>

namespace mochi::capture {

/**
 * @brief Capture dynamic simulation state and write it to a binary buffer.
 * @note Data from ECS components with @ref MOCHI_ATTRIBUTE(CaptureState) will be included.
 */
void CaptureState(entt::registry& reg, DynamicArray<uint8_t>& outData, Error& error);

/**
 * @brief Capture dynamic simulation state and write it to a human-friendly JSON string.
 * @note Data from ECS components with @ref MOCHI_ATTRIBUTE(CaptureState) will be included.
 * @note Not 1:1 with the binary format.
 */
std::string CaptureStateToJson(entt::registry& reg, bool prettyMultiLine, Error& error);

/**
 * @brief Restore dynamic simulation state from a binary buffer generated by @ref CaptureState.
 */
void RestoreState(entt::registry& reg, Span<uint8_t const> data, Error& error);

/**
 * @brief Restore dynamic simulation state like @ref RestoreState, but excluding ECS components with
 * the specified reflection attributes.
 */
void RestorePartialState(
    entt::registry& reg,
    Span<uint8_t const> data,
    Span<SReflect::TypeId const> excludedAttributes,
    Error& error);

/**
 * @brief Return true if the two state buffers encode the same state information.
 * @warning Expects valid buffers from successful calls to @ref CaptureState. Asserts otherwise.
 * @note States may be equal even if their buffers are not byte-for-byte identical.
 */
bool IsEqualState(
    entt::registry const& reg,
    Span<uint8_t const> stateA,
    Span<uint8_t const> stateB);

/**
 * @brief Register an ECS system to be invoked for each matching entity at the end of RestoreState.
 * @note This provides an opportunity to fix up derived state.
 */
template <typename... Policies, typename SystemT>
void RegisterPostRestoreSystem(SystemT system, entt::registry& reg);

/** @brief Call once on scene startup*/
void InitializeOnce(entt::registry& reg);

} // namespace mochi::capture

#include "mochi_capture_inl.h"
