# This file was @generated by mochi_gen_py. Do not modify this file by hand!!
#
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pyre-strict

from typing import Any, Callable, Iterator, Optional, Sequence, overload
import numpy as np
import numpy.typing as npt
import superdex_robotics

########################################################################################

# Template specializations
class DynamicArrayActuatorHandle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: ActuatorHandle = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[ActuatorHandle]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ActuatorHandle: ...
    def __setitem__(self, index: int, value: ActuatorHandle) -> None: ...
    def __iter__(self) -> Iterator[ActuatorHandle]: ...
    def append(self, value: ActuatorHandle) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeActuatorHandle = (
    Sequence[ActuatorHandle] | DynamicArrayActuatorHandle | npt.NDArray[Any]
)

class DynamicArrayBotActuatorPrefab:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotActuatorPrefab = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotActuatorPrefab]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotActuatorPrefab: ...
    def __setitem__(self, index: int, value: BotActuatorPrefab) -> None: ...
    def __iter__(self) -> Iterator[BotActuatorPrefab]: ...
    def append(self, value: BotActuatorPrefab) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotActuatorPrefab = (
    Sequence[BotActuatorPrefab] | DynamicArrayBotActuatorPrefab | npt.NDArray[Any]
)

class DynamicArrayBotContactOverride:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotContactOverride = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotContactOverride]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotContactOverride: ...
    def __setitem__(self, index: int, value: BotContactOverride) -> None: ...
    def __iter__(self) -> Iterator[BotContactOverride]: ...
    def append(self, value: BotContactOverride) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotContactOverride = (
    Sequence[BotContactOverride] | DynamicArrayBotContactOverride | npt.NDArray[Any]
)

class DynamicArrayBotHandle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotHandle = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotHandle]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotHandle: ...
    def __setitem__(self, index: int, value: BotHandle) -> None: ...
    def __iter__(self) -> Iterator[BotHandle]: ...
    def append(self, value: BotHandle) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotHandle = Sequence[BotHandle] | DynamicArrayBotHandle | npt.NDArray[Any]

class DynamicArrayBotJointPrefab:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotJointPrefab = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotJointPrefab]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotJointPrefab: ...
    def __setitem__(self, index: int, value: BotJointPrefab) -> None: ...
    def __iter__(self) -> Iterator[BotJointPrefab]: ...
    def append(self, value: BotJointPrefab) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotJointPrefab = (
    Sequence[BotJointPrefab] | DynamicArrayBotJointPrefab | npt.NDArray[Any]
)

class DynamicArrayBotLinearTransmissionPrefab:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotLinearTransmissionPrefab = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotLinearTransmissionPrefab]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotLinearTransmissionPrefab: ...
    def __setitem__(self, index: int, value: BotLinearTransmissionPrefab) -> None: ...
    def __iter__(self) -> Iterator[BotLinearTransmissionPrefab]: ...
    def append(self, value: BotLinearTransmissionPrefab) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotLinearTransmissionPrefab = (
    Sequence[BotLinearTransmissionPrefab] |
    DynamicArrayBotLinearTransmissionPrefab |
    npt.NDArray[Any]
)

class DynamicArrayBotLinkPrefab:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotLinkPrefab = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotLinkPrefab]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotLinkPrefab: ...
    def __setitem__(self, index: int, value: BotLinkPrefab) -> None: ...
    def __iter__(self) -> Iterator[BotLinkPrefab]: ...
    def append(self, value: BotLinkPrefab) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotLinkPrefab = (
    Sequence[BotLinkPrefab] | DynamicArrayBotLinkPrefab | npt.NDArray[Any]
)

class DynamicArrayBotSensorPrefab:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotSensorPrefab = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotSensorPrefab]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotSensorPrefab: ...
    def __setitem__(self, index: int, value: BotSensorPrefab) -> None: ...
    def __iter__(self) -> Iterator[BotSensorPrefab]: ...
    def append(self, value: BotSensorPrefab) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotSensorPrefab = (
    Sequence[BotSensorPrefab] | DynamicArrayBotSensorPrefab | npt.NDArray[Any]
)

class DynamicArrayBotSpatialTendonPrefab:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: BotSpatialTendonPrefab = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[BotSpatialTendonPrefab]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BotSpatialTendonPrefab: ...
    def __setitem__(self, index: int, value: BotSpatialTendonPrefab) -> None: ...
    def __iter__(self) -> Iterator[BotSpatialTendonPrefab]: ...
    def append(self, value: BotSpatialTendonPrefab) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeBotSpatialTendonPrefab = (
    Sequence[BotSpatialTendonPrefab] |
    DynamicArrayBotSpatialTendonPrefab |
    npt.NDArray[Any]
)

class DynamicArrayControllerHandle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: ControllerHandle = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[ControllerHandle]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ControllerHandle: ...
    def __setitem__(self, index: int, value: ControllerHandle) -> None: ...
    def __iter__(self) -> Iterator[ControllerHandle]: ...
    def append(self, value: ControllerHandle) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeControllerHandle = (
    Sequence[ControllerHandle] | DynamicArrayControllerHandle | npt.NDArray[Any]
)

class DynamicArraySensorHandle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int, value: SensorHandle = ...) -> None: ...
    @overload
    def __init__(self, sequence: Sequence[SensorHandle]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> SensorHandle: ...
    def __setitem__(self, index: int, value: SensorHandle) -> None: ...
    def __iter__(self) -> Iterator[SensorHandle]: ...
    def append(self, value: SensorHandle) -> None: ...
    def clear(self) -> None: ...
    def resize(self, size: int) -> None: ...

type ArrayLikeSensorHandle = (
    Sequence[SensorHandle] | DynamicArraySensorHandle | npt.NDArray[Any]
)

class BotFileType:
    """Type of content stored in a .superdex_bot file."""
    BOT_PREFAB: BotFileType
    """Flat bot parameters."""
    MOD_BOT_PREFAB: BotFileType
    """Mod bot recipe that produces :class:`BOT_PREFAB
    <superdex.robotics.BotFileType>`.
    """
    COUNT: BotFileType
    """Number of enum values."""
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class LinkTransformSpace:
    """Reference space for computed link transforms."""
    PARENT_FROM_LINK: LinkTransformSpace
    """Transform from each link to its parent link."""
    ROOT_FROM_PARENT: LinkTransformSpace
    """Transform from each link to the root link."""
    COUNT: LinkTransformSpace
    """Number of enum values."""
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class RoboticsHandle:
    """Shared base handle for bots, controllers, sensors, and actuators. The distinct
    derived handle types below encode the component kind in the C++ type
    (compile-time safety); all share this base's raw value and validity check.
    """
    value: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: int = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: RoboticsHandle) -> bool: ...
    def __hash__(self) -> int: ...
    def is_valid(self) -> bool: ...

class BotHandle(RoboticsHandle):
    """Distinct handle identifying a bot in its owning
    :class:`~superdex.robotics.RoboticsContext`.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: int = ...) -> None: ...

class ControllerHandle(RoboticsHandle):
    """Distinct handle identifying a controller in its owning
    :class:`~superdex.robotics.RoboticsContext`.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: int = ...) -> None: ...

class SensorHandle(RoboticsHandle):
    """Distinct handle identifying a sensor in its owning
    :class:`~superdex.robotics.RoboticsContext`.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: int = ...) -> None: ...

class ActuatorHandle(RoboticsHandle):
    """Distinct handle identifying an actuator in its owning
    :class:`~superdex.robotics.RoboticsContext`.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: int = ...) -> None: ...

class BotJointPrefab(mochi_physics.prefab.ArticulatedJointPrefab):
    """Parameters describing a single joint in a bot."""
    effort_limit: float
    """Maximum effort magnitude that may be applied to actuate this joint [N·m for
    revolute, N for prismatic]. Interpreted by regime: a negative value (default
    :const:`~superdex.robotics.EFFORT_UNBOUNDED`) is unbounded; 0 is non-actuated
    (no effort can be applied, though the joint still moves freely within its range
    under external forces); a positive value is a finite limit. This is advisory
    metadata — it is not copied into the physics articulation, so the sim enforces
    nothing on its own; controllers may read it (e.g. to clamp their output).
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        name: str = ...,
        type: mochi_physics.ArticulatedJointType | int = ...,
        parent_link_from_joint: mochi_physics.TransformRT = ...,
        axis: mochi_physics.Real3Like = ...,
        friction: mochi_physics.ArticulatedJointFrictionParams = ...,
        inertia: Optional[float] = ...,
        min_limit: Optional[mochi_physics.Real3Like] = ...,
        max_limit: Optional[mochi_physics.Real3Like] = ...,
        limit_stiffness: float = ...,
        limit_damping: float = ...,
        effort_limit: float = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotSensorPrefab:
    """Parameters describing a single sensor in a bot."""
    type: str
    """Registered sensor type (e.g., "SENSOR_CAMERA")."""
    name: str
    """Human-readable, findable identifier for this sensor instance."""
    parent_from_sensor: mochi_physics.TransformRT
    """Sensor pose relative to the associated link's actor (aFromB convention: maps
    sensor-frame coordinates into the link frame). Chain to world via
    SensorBase::GetWorldTransform.
    """
    params: str
    """Sensor parameters: a path to a .superdex_sensor JSON file or inline JSON. Empty
    uses defaults.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        type: str = ...,
        name: str = ...,
        parent_from_sensor: mochi_physics.TransformRT = ...,
        params: str = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotActuatorPrefab:
    """Parameters describing a single actuator in a bot."""
    type: str
    """Registered actuator type."""
    name: str
    """Human-readable, findable identifier for this actuator instance."""
    params: str
    """Actuator parameters: a path to a params JSON file or inline JSON. Empty uses
    defaults.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, type: str = ..., name: str = ..., params: str = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotLinkPrefab(mochi_physics.prefab.ArticulatedLinkPrefab):
    """Parameters describing a single link (body) in a bot."""
    @property
    def sensors(self) -> DynamicArrayBotSensorPrefab:
        """Sensors attached to this link. Optional; may be empty."""
    @sensors.setter
    def sensors(self, value: ArrayLikeBotSensorPrefab) -> None: ...
    @property
    def actuators(self) -> DynamicArrayBotActuatorPrefab:
        """Actuators attached to this link. Optional; may be empty."""
    @actuators.setter
    def actuators(self, value: ArrayLikeBotActuatorPrefab) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        name: str = ...,
        parent_link: int = ...,
        parent_joint_from_link: mochi_physics.TransformRT = ...,
        shape: mochi_physics.ShapeHandle = ...,
        layer: str = ...,
        collider_type: mochi_physics.ColliderType | int = ...,
        contact: mochi_physics.ContactParams = ...,
        has_gravity: bool = ...,
        density: Optional[float] = ...,
        mass: Optional[float] = ...,
        center_of_mass: Optional[mochi_physics.Real3Like] = ...,
        moment_of_inertia: Optional[mochi_physics.Real6Like] = ...,
        boundary_element_type: mochi_physics.ActorBoundaryElementType | int = ...,
        boundary_subsampling: Optional[mochi_physics.BoundarySubsamplingParams] = ...,
        shape_file: str = ...,
        shape_scale: mochi_physics.Real3Like = ...,
        shape_rotation: mochi_physics.QuaternionLike = ...,
        shape_translation: mochi_physics.Real3Like = ...,
        render_model_file: str = ...,
        render_model_scale: mochi_physics.Real3Like = ...,
        render_model_rotation: mochi_physics.QuaternionLike = ...,
        render_model_translation: mochi_physics.Real3Like = ...,
        sensors: ArrayLikeBotSensorPrefab = ...,
        actuators: ArrayLikeBotActuatorPrefab = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotContactOverride:
    """Used to explicitly enable or disable contact between links in a bot. By default,
    all bots will spawn with contact disabled between links and their first ancestor
    with a physics body not connected via a Hard joint. This structure can be used
    to either reenable contact on those pairs, or disable contact between links that
    are not strictly child-parent. Overrides are applied on bot link actors after
    spawn using :meth:`~superdex.physics.Scene.enable_actor_contact_symmetric`.

    See Also:
        :attr:`~superdex.robotics.BotPrefab.contact_overrides`,
        :meth:`~superdex.physics.Scene.enable_actor_contact_symmetric`
    """
    link_a: str
    """The first link in the pair."""
    link_b: str
    """The second link in the pair."""
    enable: bool
    """Should contact between the pair be enabled?"""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        link_a: str = ...,
        link_b: str = ...,
        enable: bool = ...,
    ) -> None: ...

class BotTransmissionPrefab(
    mochi_physics.experimental.DisplacementControlActuatorParams
):
    """Common parameters for bot transmissions (linear transmissions and spatial
    tendons).

    Holds fields shared by transmission-like actuators that couple joint DOFs via a
    displacement-control actuator. Provides the display name and inherits actuator
    tuning parameters from mochi::experimental::DisplacementControlActuatorParams.
    """
    name: str
    """Human-readable label (used by the editor UI; not consumed by the runtime API)."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        target_displacement: float = ...,
        stiffness: float = ...,
        damping: float = ...,
        allow_compressive_force: bool = ...,
        name: str = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotLinearTransmissionPrefab(BotTransmissionPrefab):
    """Parameters describing a single linear transmission attached to a bot.

    Mirrors mochi::experimental::LinearTransmissionParams with an added display
    :attr:`~superdex.robotics.BotTransmissionPrefab.name` field and SReflect markup
    so it can live inside :class:`~superdex.robotics.BotPrefab` and round-trip
    through the bot's JSON serialization. The three joint arrays
    (:attr:`joint_indices`, :attr:`joint_coefficients`, :attr:`joint_axis_disps`)
    must always be the same length, with one entry per joint the transmission
    traverses. The remaining fields are inherited from
    :class:`~superdex.robotics.BotTransmissionPrefab` which inherits
    mochi::experimental::DisplacementControlActuatorParams so that one
    displacement-control actuator can be configured alongside each transmission.
    """
    @property
    def joint_indices(self) -> mochi_physics.DynamicArrayInt:
        """Indices into :attr:`~superdex.robotics.BotPrefab.joints` identifying which
        joints the transmission traverses.
        """
    @joint_indices.setter
    def joint_indices(self, value: mochi_physics.ArrayLikeInt) -> None: ...
    @property
    def joint_coefficients(self) -> mochi_physics.DynamicArrayReal:
        """Transmission Jacobian entry at each joint [m / joint-DoF units for a tendon,
        dimensionless for a gearbox]. Sign encodes direction: positive if the
        transmission displacement increases with the joint DoF, negative if it
        decreases.
        """
    @joint_coefficients.setter
    def joint_coefficients(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def joint_axis_disps(self) -> mochi_physics.DynamicArrayReal:
        """Displacement along the joint axis [m] for the transmission attachment point
        at
        each joint. This allows the transmission to be offset from the joint origin
        along the axis.
        """
    @joint_axis_disps.setter
    def joint_axis_disps(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        target_displacement: float = ...,
        stiffness: float = ...,
        damping: float = ...,
        allow_compressive_force: bool = ...,
        name: str = ...,
        joint_indices: mochi_physics.ArrayLikeInt = ...,
        joint_coefficients: mochi_physics.ArrayLikeReal = ...,
        joint_axis_disps: mochi_physics.ArrayLikeReal = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotSpatialTendonPrefab(BotTransmissionPrefab):
    """Parameters describing a single spatial tendon attached to a bot.

    Mirrors mochi::experimental::SpatialTendonParams with an added display
    :attr:`~superdex.robotics.BotTransmissionPrefab.name` field and SReflect markup
    so it can live inside :class:`~superdex.robotics.BotPrefab` and round-trip
    through the bot's JSON serialization. The ordered :attr:`routing_elements` list
    defines waypoint and linear-joint elements traversed by the tendon. The
    remaining fields are inherited from
    :class:`~superdex.robotics.BotTransmissionPrefab` which inherits
    mochi::experimental::DisplacementControlActuatorParams so that one
    displacement-control actuator can be configured alongside each tendon.
    """
    @property
    def routing_elements(self) -> mochi_physics.DynamicArrayRoutingElement:
        """Ordered routing elements defining the tendon path. Must contain at least one
        element, and every waypoint must be adjacent to another waypoint.
        """
    @routing_elements.setter
    def routing_elements(
        self,
        value: mochi_physics.ArrayLikeRoutingElement,
    ) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        target_displacement: float = ...,
        stiffness: float = ...,
        damping: float = ...,
        allow_compressive_force: bool = ...,
        name: str = ...,
        routing_elements: mochi_physics.ArrayLikeRoutingElement = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BotPrefab:
    """Complete parameter set for a bot."""
    name: str
    """Bot name."""
    @property
    def joints(self) -> DynamicArrayBotJointPrefab:
        """Joint parameters for each joint in the articulation."""
    @joints.setter
    def joints(self, value: ArrayLikeBotJointPrefab) -> None: ...
    @property
    def links(self) -> DynamicArrayBotLinkPrefab:
        """Link parameters for each link in the articulation."""
    @links.setter
    def links(self, value: ArrayLikeBotLinkPrefab) -> None: ...
    world_from_root: mochi_physics.TransformRT
    """Transform from the root link to the world frame."""
    @property
    def default_pose(self) -> mochi_physics.DynamicArrayReal:
        """Default pose (array of joint DOF angles/translations) used when spawning the
        bot.
        """
    @default_pose.setter
    def default_pose(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def linear_transmissions(self) -> DynamicArrayBotLinearTransmissionPrefab:
        """Linear transmissions that couple multiple joint DOFs via per-joint
        coefficients.
        Each entry produces one mochi::experimental::LinearTransmissionParams at
        instantiation time.
        """
    @linear_transmissions.setter
    def linear_transmissions(
        self,
        value: ArrayLikeBotLinearTransmissionPrefab,
    ) -> None: ...
    @property
    def spatial_tendons(self) -> DynamicArrayBotSpatialTendonPrefab:
        """Spatial tendons routed through waypoint and linear-joint elements. Each entry
        produces one mochi::experimental::SpatialTendonParams at instantiation time.
        """
    @spatial_tendons.setter
    def spatial_tendons(self, value: ArrayLikeBotSpatialTendonPrefab) -> None: ...
    @property
    def contact_overrides(self) -> DynamicArrayBotContactOverride:
        """Array of link-link contact override pairs."""
    @contact_overrides.setter
    def contact_overrides(self, value: ArrayLikeBotContactOverride) -> None: ...
    @property
    def cycles(self) -> mochi_physics.DynamicArrayArticulatedCycleJointParams:
        """Cycle-closing joints for closed-loop mechanisms (e.g. four-bar linkages,
        parallel grippers). Each entry becomes one mochi::ArticulatedActorParams::cycles
        entry at instantiation time. Link references
        (mochi::ArticulatedCycleJointParams::parentLink /
        mochi::ArticulatedCycleJointParams::childLink) are int indices into
        :attr:`~superdex.robotics.BotPrefab.links`.
        """
    @cycles.setter
    def cycles(
        self,
        value: mochi_physics.ArrayLikeArticulatedCycleJointParams,
    ) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        name: str = ...,
        joints: ArrayLikeBotJointPrefab = ...,
        links: ArrayLikeBotLinkPrefab = ...,
        world_from_root: mochi_physics.TransformRT = ...,
        default_pose: mochi_physics.ArrayLikeReal = ...,
        linear_transmissions: ArrayLikeBotLinearTransmissionPrefab = ...,
        spatial_tendons: ArrayLikeBotSpatialTendonPrefab = ...,
        contact_overrides: ArrayLikeBotContactOverride = ...,
        cycles: mochi_physics.ArrayLikeArticulatedCycleJointParams = ...,
    ) -> None: ...

class RoboticsContext:
    """Resource owner for bots, controllers, sensors, and actuators.

    Owns the memory for bots, controllers, sensors, and actuators created through
    it.
    """
    def create_controller(
        self,
        type_name: str,
        prefab: Optional[BotPrefab],
        robot: Optional[mochi_physics.Actor],
        name: str = ...,
    ) -> ControllerHandle:
        """Create a controller of the given type for robot. Harvests model-derived
        configuration (e.g. per-joint effort limits) from the optional borrowed prefab:
        pass None to create on a raw articulated actor with no model (the prefab must
        outlive the controller otherwise).

        robot may also be None, to drive a real robot with observations pushed in from
        outside instead of read off a Mochi articulation. Anything that needs the
        articulation (e.g. reading a Jacobian) then has to be supplied externally, and
        the controller reports an error if asked for it. A controller that cannot work
        at all without a simulation rejects the None actor itself — see
        :class:`~superdex.robotics.ControllerMochiArticulatedPose`, which drives Mochi's
        built-in implicit PD controller.

        The owning bot is inferred from robot (see
        :meth:`~superdex.robotics.RoboticsContext.get_bot_containing_actor`): if that
        actor is a bot's articulation or one of its link actors, the controller is
        recorded against that bot, found by the bot-scoped finders, and destroyed with
        it; otherwise it has no owning bot.
        :meth:`~superdex.robotics.Bot.create_controller` is the more direct way to
        create one on a bot you already hold, and also carries an instance name.

        Args:
            type_name (str): Registered controller type name.
            prefab (Optional[BotPrefab]): Optional borrowed robot-model description; may
                be None and must outlive the created controller.
            robot (Optional[Actor]): Articulated actor to control, or None for
                externally supplied observations.
            name (str): Instance name used by the name-based finders; need not be
                unique.

        Returns:
            Handle to the created controller, or an invalid handle on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_controller(self, handle: ControllerHandle) -> Optional[ControllerBase]:
        """Get the controller associated with the given handle.

        Args:
            handle (ControllerHandle): Controller handle to resolve.

        Returns:
            Context-owned controller, or None if the handle is invalid or stale.
        """
    def destroy_controller(self, handle: ControllerHandle) -> None:
        """Destroy the controller associated with the given handle.

        Args:
            handle (ControllerHandle): Controller handle to destroy; invalid or stale
                handles are ignored.
        """
    def is_valid_controller(self, handle: ControllerHandle) -> bool:
        """Check whether a handle refers to a live controller.

        Args:
            handle (ControllerHandle): Controller handle to check.

        Returns:
            True if the handle resolves to a live controller.
        """
    def create_sensor(
        self,
        type_name: str,
        link_actor: Optional[mochi_physics.Actor],
        name: str = ...,
        param_args: str = ...,
    ) -> SensorHandle:
        """Create a sensor of the given type on the given link actor. paramArgs is an
        optional params file path or inline JSON string consumed by the factory; pass an
        empty view to use default-constructed parameters. name is the instance name used
        by :meth:`~superdex.robotics.RoboticsContext.find_sensors_by_name` and need not
        be unique. The owning bot is inferred from linkActor. Returns a handle. For
        bot-owned sensors, prefer declaring them in the
        :class:`~superdex.robotics.BotPrefab` so they are auto-instantiated and
        destroyed with the bot.

        Args:
            type_name (str): Registered sensor type name.
            link_actor (Optional[Actor]): Actor to attach the sensor to, or None for an
                actor-less sensor.
            name (str): Instance name used by the name-based finders; need not be
                unique.
            param_args (str): Params file path or inline JSON; empty uses defaults.

        Returns:
            Handle to the created sensor, or an invalid handle on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_sensor(self, handle: SensorHandle) -> Optional[SensorBase]:
        """Get the sensor associated with the given handle. Returns None if invalid.
        Downcast to the concrete sensor type as needed (e.g.
        ``static_cast<CameraSensor*>(GetSensor(handle))``).

        Args:
            handle (SensorHandle): Sensor handle to resolve.

        Returns:
            Context-owned sensor, or None if the handle is invalid or stale.
        """
    def destroy_sensor(self, handle: SensorHandle) -> None:
        """Destroy the sensor associated with the given handle.

        Args:
            handle (SensorHandle): Sensor handle to destroy; invalid or stale handles
                are ignored.
        """
    def is_valid_sensor(self, handle: SensorHandle) -> bool:
        """Check whether a handle refers to a live sensor.

        Args:
            handle (SensorHandle): Sensor handle to check.

        Returns:
            True if the handle resolves to a live sensor.
        """
    def create_actuator(
        self,
        type_name: str,
        link_actor: mochi_physics.Actor,
        name: str = ...,
        param_args: str = ...,
    ) -> ActuatorHandle:
        """Create an actuator of the given type on the given link actor. Unlike a
        sensor,
        an actuator always drives a body, so linkActor is required: passing None sets an
        error and returns an invalid handle. paramArgs is an optional params file path
        or inline JSON string; empty uses default-constructed parameters. name is the
        instance name used by
        :meth:`~superdex.robotics.RoboticsContext.find_actuators_by_name` and need not
        be unique. The owning bot is inferred from linkActor. Returns a handle. For
        bot-owned actuators, prefer declaring them in the
        :class:`~superdex.robotics.BotPrefab` so they are auto-instantiated and
        destroyed with the bot.

        Args:
            type_name (str): Registered actuator type name.
            link_actor (Actor): Actor the actuator drives; must not be None.
            name (str): Instance name used by the name-based finders; need not be
                unique.
            param_args (str): Params file path or inline JSON; empty uses defaults.

        Returns:
            Handle to the created actuator, or an invalid handle on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_actuator(self, handle: ActuatorHandle) -> Optional[ActuatorBase]:
        """Get the actuator associated with the given handle. Returns None if invalid.
        Downcast to the concrete actuator type as needed.

        Args:
            handle (ActuatorHandle): Actuator handle to resolve.

        Returns:
            Context-owned actuator, or None if the handle is invalid or stale.
        """
    def destroy_actuator(self, handle: ActuatorHandle) -> None:
        """Destroy the actuator associated with the given handle.

        Args:
            handle (ActuatorHandle): Actuator handle to destroy; invalid or stale
                handles are ignored.
        """
    def is_valid_actuator(self, handle: ActuatorHandle) -> bool:
        """Check whether a handle refers to a live actuator.

        Args:
            handle (ActuatorHandle): Actuator handle to check.

        Returns:
            True if the handle resolves to a live actuator.
        """
    def get_bot(self, handle: BotHandle) -> Optional[Bot]:
        """Get the bot associated with the given handle.

        Args:
            handle (BotHandle): Bot handle to resolve.

        Returns:
            Context-owned bot, or None if the handle is invalid or the bot was
            destroyed.
        """
    def is_valid_bot(self, handle: BotHandle) -> bool:
        """Check whether a handle refers to a live bot.

        Args:
            handle (BotHandle): Bot handle to check.

        Returns:
            True if the handle resolves to a live bot.
        """
    def get_bot_containing_actor(
        self,
        actor: Optional[mochi_physics.Actor],
    ) -> Optional[Bot]:
        """Find the bot containing actor. Accepts either a bot's articulation actor or
        any
        of its link actors. Returns None when the actor is contained by no bot, which is
        a valid result: a scene may hold standalone actors and articulations from plain
        mochi prefabs alongside its bots. A None actor also returns None.

        Args:
            actor (Optional[Actor]): Actor to locate; may be None.

        Returns:
            Context-owned bot containing the actor, or None if none.
        """
    def is_controller_type_registered(self, type_name: str) -> bool:
        """Check whether a controller type name is registered (creatable via
        CreateController). Lets the scene loader skip unknown types gracefully (e.g.
        internal-only types in a public build).

        Args:
            type_name (str): Registered type name to check.

        Returns:
            True if a controller factory is registered for the type name.
        """
    def is_sensor_type_registered(self, type_name: str) -> bool:
        """Check whether a sensor type name is registered (creatable via CreateSensor).
        Mirrors :meth:`~superdex.robotics.RoboticsContext.is_controller_type_registered`
        / :meth:`~superdex.robotics.RoboticsContext.is_actuator_type_registered`.

        Args:
            type_name (str): Registered type name to check.

        Returns:
            True if a sensor factory is registered for the type name.
        """
    def is_actuator_type_registered(self, type_name: str) -> bool:
        """Check whether an actuator type name is registered (creatable via
        CreateActuator).

        Args:
            type_name (str): Registered type name to check.

        Returns:
            True if an actuator factory is registered for the type name.
        """
    def find_controllers_by_name(self, name: str) -> DynamicArrayControllerHandle:
        """Find all controllers whose instance name equals name, across every controller
        in
        this context. Instance names are not unique, so any number of handles may be
        returned (empty if none match).

        Args:
            name (str): Exact instance name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_controllers_by_type(self, type_name: str) -> DynamicArrayControllerHandle:
        """Find all controllers of the given registered typeName. Returns every match;
        empty if none.

        Args:
            type_name (str): Exact registered type name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_sensors_by_name(self, name: str) -> DynamicArraySensorHandle:
        """Find all sensors whose instance name equals name, across every sensor in this
        context (including scene-level sensors that have no owning bot). Returns every
        match; empty if none.

        Args:
            name (str): Exact instance name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_sensors_by_type(self, type_name: str) -> DynamicArraySensorHandle:
        """Find all sensors of the given registered typeName. Returns every match; empty
        if
        none.

        Args:
            type_name (str): Exact registered type name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_actuators_by_name(self, name: str) -> DynamicArrayActuatorHandle:
        """Find all actuators whose instance name equals name, across every actuator in
        this context. Returns every match; empty if none.

        Args:
            name (str): Exact instance name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_actuators_by_type(self, type_name: str) -> DynamicArrayActuatorHandle:
        """Find all actuators of the given registered typeName. Returns every match;
        empty
        if none.

        Args:
            type_name (str): Exact registered type name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_bots_by_name(self, name: str) -> DynamicArrayBotHandle:
        """Find all bots whose name (from :attr:`~superdex.robotics.BotPrefab.name`)
        equals
        name. Bot names are not unique (multiple bots may share a prefab name), so any
        number of handles may be returned (empty if none). There is no FindBotsByType: a
        bot has no registered type.

        Args:
            name (str): Exact bot name to match.

        Returns:
            Handles of every matching live bot; empty if none.
        """

class ComponentBase:
    """Base class for all bots components (controllers, sensors, actuators). Provides
    common state: the associated actor's stale-safe identity, a validity flag, and
    the Destroy pattern. The validity flag is set to false by RoboticsContext before
    deletion, allowing dangling-pointer detection alongside generational handles.

    The associated actor is NOT cached as a raw pointer. Its stale-safe identity
    (:class:`~superdex.physics.ActorHandle` / :class:`~superdex.physics.SceneHandle`
    / owning Mochi context) is retained and :meth:`get_actor` resolves the live
    :class:`~superdex.physics.Actor`\\* on demand, yielding None once the owning
    scene (or the actor) has been destroyed. A component that outlives its mochi
    Scene (e.g. the Scene was destroyed before the RoboticsContext) therefore never
    dereferences a dangling Actor* — callers check :meth:`get_actor` for None. This
    assumes the mochi Mochi context outlives the RoboticsContext — the outermost
    lifetime in the mochi ownership graph.
    """
    def is_valid(self) -> bool:
        """Whether this component remains usable. Returns false after its owning
        :class:`~superdex.robotics.RoboticsContext` destroys it.

        Returns:
            True while the component is live.
        """
    def get_actor(self) -> Optional[mochi_physics.Actor]:
        """Resolve the live :class:`~superdex.physics.Actor`\\* this component is bound
        to,
        or None if it was constructed without an actor or its owning scene/actor has
        since been destroyed. Resolved on demand from the stale-safe handle each call
        (an O(1) scene lookup), so it is always current and never returns a dangling
        pointer — dereference only after a None check.

        Returns:
            Live associated actor, or None if none is available.
        """
    def get_owning_bot(self) -> Optional[Bot]:
        """The bot this component was created on, or None if it was created directly on
        an
        actor (not via a bot) — e.g. a scene-level sensor or a controller built on a raw
        articulation. Used to scope FindByName / FindByType to a single bot and to drive
        DestroyBot's component cascade. Borrowed: the owning bot is owned by the
        RoboticsContext, which destroys a bot's components before the bot itself, so
        this never dangles. Held as a raw pointer (not a handle) because a bot is not
        scene-owned, so the stale-safety the actor handles provide is unnecessary here.

        Returns:
            Owning bot, or None if this component has no owning bot.
        """
    def get_name(self) -> str:
        """This component's instance name, or empty if it was created without one. Names
        are NOT required to be unique, so name-based lookups (FindByName) may return
        multiple matches.

        Returns:
            Instance name; empty if unnamed.
        """
    def get_type_name(self) -> str:
        """This component's registered type name (e.g. "BASIC_OSC_PD", "SENSOR_CAMERA"),
        reported polymorphically. Declared here so controllers, sensors, and actuators
        can be searched by type uniformly (FindByType); each component kind implements
        it.

        Returns:
            Registered component type name.
        """
    def reset(self) -> None:
        """Reset internal state without destroying the component. Parameters are
        preserved.
        Use between episodes to clear stale state (e.g., derivative tracking, timing
        diagnostics).
        """

class ControllerBase(ComponentBase):
    """Base class for all controllers. Inherits common lifecycle from ComponentBase.
    Controllers are identified by string names via RoboticsContext registration, not
    enums.
    """
    def configure_from_scene_entry(self, param_args: str, init_args: str) -> None:
        """Configure this controller from serialized parameter and initialization
        arguments. paramArgs is either a params file path or inline JSON; empty uses
        defaults. initArgs is a controller-specific file path or inline JSON, for
        example carrying baseLinkName/eeLinkName for link-resolved controllers.
        Implementations typically deserialize it into a small reflected init-args struct
        and ignore unrecognized framework keys.

        Pure virtual: every controller must implement this uniform configuration entry
        point. A controller that cannot support serialized configuration should set an
        error with a clear message rather than silently succeeding.

        Args:
            param_args (str): Params file path or inline JSON; empty uses defaults.
            init_args (str): Controller-specific init-argument file path or inline JSON.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class ControllerBasicOscPdParams:
    """Basic operational-space PD controller parameters.

    Minimal parameter set for a robot-agnostic task-space impedance controller. See
    ControllerBasicOscPd for details.
    """
    kp_p: float
    """Position gain [N/m]"""
    kd_p: float
    """Position damping gain [Ns/m]"""
    kp_r: float
    """Rotation gain [Nm/rad]"""
    kd_r: float
    """Rotation damping gain [Nms/rad]"""
    b_apply_max_error_magnitude_normalization: bool
    """If true, renormalize the task-space error so translation and rotation errors
    stay below their configured maximums, keeping the force direction consistent.
    Requires positive maxTranslationError and maxRotationError.
    """
    max_translation_error: float
    """Max translation error for normalization in control space [m]. Must be positive
    when enabled.
    """
    max_rotation_error: float
    """Max rotation error for normalization in control space [rad]. Must be positive
    when enabled.
    """
    ee_link_from_ee: mochi_physics.TransformRT
    """The transform of the actual end-effector in the end-effector link space"""
    b_apply_max_osc_torque_normalization: bool
    """If true, scale the output efforts down uniformly so that no controlled DOF
    exceeds the per-joint effort limit harvested from the controller's BotPrefab
    (see Initialize), preserving the task-space force direction. Requires the
    controller to have been constructed with a BotPrefab; only joints with a finite
    (positive) effortLimit constrain the scaling — unbounded (negative) and
    non-actuated (zero) joints are ignored.
    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        kp_p: float = ...,
        kd_p: float = ...,
        kp_r: float = ...,
        kd_r: float = ...,
        b_apply_max_error_magnitude_normalization: bool = ...,
        max_translation_error: float = ...,
        max_rotation_error: float = ...,
        ee_link_from_ee: mochi_physics.TransformRT = ...,
        b_apply_max_osc_torque_normalization: bool = ...,
    ) -> None: ...
    @staticmethod
    def load_from_file(path: str) -> ControllerBasicOscPdParams:
        """Load controller parameters from a JSON file.

        Args:
            path (str): Path to a .superdex_controller JSON file.

        Returns:
            Loaded parameters, or default-constructed on failure.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def save_to_file(self, path: str) -> None:
        """Save controller parameters to a JSON file.

        Args:
            path (str): Destination file path.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class ControllerBasicOscPdObsv:
    """Observation state — robot state variables read each control step. Fill it with
    GetCurrentObservationsFromMochi to read the live simulation, or populate it
    directly from an external state source (e.g., a real robot).
    """
    @property
    def dof_positions(self) -> mochi_physics.DynamicArrayReal:
        """All DOF positions [rad or m]"""
    @dof_positions.setter
    def dof_positions(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def dof_velocities(self) -> mochi_physics.DynamicArrayReal:
        """All DOF velocities [rad/s or m/s]"""
    @dof_velocities.setter
    def dof_velocities(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    world_from_root: mochi_physics.TransformRT
    """Root link pose in world frame"""
    world_from_ee_link: mochi_physics.TransformRT
    """EE link pose in world frame"""
    @property
    def ee_jacobian(self) -> mochi_physics.DynamicArrayReal:
        """6×numDofs EE Jacobian in world frame (row-major)"""
    @ee_jacobian.setter
    def ee_jacobian(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        dof_positions: mochi_physics.ArrayLikeReal = ...,
        dof_velocities: mochi_physics.ArrayLikeReal = ...,
        world_from_root: mochi_physics.TransformRT = ...,
        world_from_ee_link: mochi_physics.TransformRT = ...,
        ee_jacobian: mochi_physics.ArrayLikeReal = ...,
    ) -> None: ...

class ControllerBasicOscPdTarget:
    """Target setpoint for the controller."""
    root_from_target_ee: mochi_physics.TransformRT
    """Target EE pose in root frame"""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        root_from_target_ee: mochi_physics.TransformRT = ...,
    ) -> None: ...

class ControllerBasicOscPd(ControllerBase):
    """Basic operational-space PD (impedance) controller for robotic arms.

    Computes joint torques via the Jacobian transpose method: tau = J^T * F, where F
    = Kp * pose_error + Kd * velocity_error combines position/rotation tracking
    errors with PD gains. This is the minimal, robot-agnostic core of
    operational-space control:

    - No nullspace or posture bias. Redundant (extra-DOF) arms are free to drift in
      the nullspace; only the end-effector pose is regulated.
    - Per-DOF effort clamping (direction-preserving vector scaling), enabled by
      default; the per-joint effort limits are harvested from the controller's
      BotPrefab (see Initialize).
    - No joint/velocity-limit avoidance, friction/gravity compensation, or inertia
      decoupling; those belong to richer controllers (see the internal OSC
      variants).

    Intended as a clean, open-sourceable baseline that works on any articulated arm
    without robot-specific tuning tables.
    """
    @staticmethod
    def type_name() -> str:
        """Registration type name for this controller (see
        RoboticsContext::RegisterControllerType).

        Returns:
            This controller's registration type name.
        """
    def initialize(self, base_link_name: str, ee_link_name: str) -> None:
        """Two-phase initialization: resolve base and end-effector links by name. Must
        be
        called after creation and before
        :meth:`~superdex.robotics.ControllerBasicOscPd.compute_output`.

        Args:
            base_link_name (str): Name of the base link (root of control chain).
            ee_link_name (str): Name of the end-effector link.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_params(self) -> ControllerBasicOscPdParams:
        """Get controller parameters.

        Returns:
            The params.
        """
    def set_params(self, params: ControllerBasicOscPdParams) -> None:
        """Set controller parameters.

        Args:
            params (ControllerBasicOscPdParams): Params.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_controlled_dofs(self) -> mochi_physics.SpanConstInt:
        """Get the controlled DOF indices (between base and end-effector links).

        Returns:
            The controlled dofs.
        """
    def get_controlled_links(self) -> mochi_physics.SpanConstInt:
        """Get the controlled link indices (between base and end-effector links).

        Returns:
            The controlled links.
        """
    def get_ee_link_index(self) -> int:
        """Get the end-effector link index.

        Returns:
            The eelink index.
        """
    def get_current_observations_from_mochi(self) -> ControllerBasicOscPdObsv:
        """Read current robot state from the Mochi actor.

        Returns:
            Observation struct populated from the actor's current state.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def compute_output(
        self,
        obsv: ControllerBasicOscPdObsv,
        target: ControllerBasicOscPdTarget,
    ) -> mochi_physics.SpanConstReal:
        """Compute control efforts from observation state and target setpoint.

        Args:
            obsv (ControllerBasicOscPdObsv): Current robot state (positions, velocities,
                transforms).
            target (ControllerBasicOscPdTarget): Target setpoint.

        Returns:
            Efforts for all DOFs [Nm]. Uncontrolled DOFs are set to 0. Empty span on
            error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class ControllerMochiArticulatedPoseParams:
    """ControllerMochiArticulatedPose parameters."""
    pose_controller_params: mochi_physics.PoseControllerParams
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        pose_controller_params: mochi_physics.PoseControllerParams = ...,
    ) -> None: ...
    @staticmethod
    def load_from_file(path: str) -> ControllerMochiArticulatedPoseParams:
        """Load controller parameters from a JSON file.

        Args:
            path (str): Path to a .superdex_controller JSON file.

        Returns:
            Loaded parameters, or default-constructed on failure.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def save_to_file(self, path: str) -> None:
        """Save controller parameters to a JSON file.

        Args:
            path (str): Destination file path.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class ControllerMochiArticulatedPoseObsv:
    """Observation state (empty — this controller is target-driven)."""
    def __init__(self) -> None: ...

class ControllerMochiArticulatedPoseTarget:
    """Target to drive the ArticulatedPoseController toward. Provide exactly one of
    :attr:`local_to_parent_transforms` or :attr:`pose_dofs`.
    """
    world_from_root: mochi_physics.TransformRT
    """Root link pose in world frame"""
    @property
    def local_to_parent_transforms(self) -> mochi_physics.DynamicArrayTransformRT:
        """Per-link LocalToParent transforms"""
    @local_to_parent_transforms.setter
    def local_to_parent_transforms(
        self,
        value: mochi_physics.ArrayLikeTransformRT,
    ) -> None: ...
    @property
    def pose_dofs(self) -> mochi_physics.DynamicArrayReal:
        """Non-root joint DOFs; root DOFs are derived from worldFromRoot"""
    @pose_dofs.setter
    def pose_dofs(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        world_from_root: mochi_physics.TransformRT = ...,
        local_to_parent_transforms: mochi_physics.ArrayLikeTransformRT = ...,
        pose_dofs: mochi_physics.ArrayLikeReal = ...,
    ) -> None: ...

class ControllerMochiArticulatedPose(ControllerBase):
    """ControllerMochiArticulatedPose -- drives a mochi ArticulatedPoseController via
    either per-link LocalToParent transforms (converted to world-space targets) or
    non-root pose DOFs combined with a world-space root transform.
    """
    @staticmethod
    def type_name() -> str:
        """Registration type name for this controller (see
        RoboticsContext::RegisterControllerType).

        Returns:
            This controller's registration type name.
        """
    def initialize(self, remove_existing: bool) -> None:
        """Add a mochi ArticulatedPoseController to the actor using the default/current
        params. Mochi ArticulatedPoseController is a singleton per articulation so only
        one controller can be active at a time. Calling commands on multiple controllers
        at the same time will result in overwriting commands. Must be called after
        SetParams and before ComputeOutput.

        Args:
            remove_existing (bool): If true, removes any existing
                ArticulatedPoseController on the actor before adding a new one. If
                false, an existing controller causes an error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_params(self) -> ControllerMochiArticulatedPoseParams:
        """Get controller parameters.

        Returns:
            The params.
        """
    def set_params(self, params: ControllerMochiArticulatedPoseParams) -> None:
        """Set controller parameters.

        Args:
            params (ControllerMochiArticulatedPoseParams): Params.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def compute_output(
        self,
        obsv: ControllerMochiArticulatedPoseObsv,
        target: ControllerMochiArticulatedPoseTarget,
    ) -> mochi_physics.SpanConstReal:
        """Forward targets to the internal pose controller.

        Args:
            obsv (ControllerMochiArticulatedPoseObsv): Unused (empty).
            target (ControllerMochiArticulatedPoseTarget): Target poses: either
                worldFromRoot +
                :attr:`~superdex.robotics.ControllerMochiArticulatedPoseTarget.local_to_parent_transforms`
                (link-transform path), or worldFromRoot +
                :attr:`~superdex.robotics.ControllerMochiArticulatedPoseTarget.pose_dofs`
                (pose-DOF path). Exactly one must be provided.

        Returns:
            Empty span — control is applied internally via the pose controller.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class Bot:
    """Runtime interface to a bot instance in a :class:`~superdex.physics.Scene`.

    A :class:`~superdex.robotics.Bot` wraps a single articulated
    :class:`~superdex.physics.Actor` with the controllers, sensors, and actuators
    created for it. Bots are created via :func:`~superdex.robotics.create_bot` and
    destroyed via :func:`~superdex.robotics.destroy_bot`. The
    :class:`~superdex.robotics.RoboticsContext` owns the bot memory allocated and
    deallocated by these functions, respectively. The raw
    :class:`~superdex.robotics.Bot`\\* returned by
    :func:`~superdex.robotics.create_bot` remains valid until
    :func:`~superdex.robotics.destroy_bot` is called or the
    :class:`~superdex.robotics.RoboticsContext` is destroyed.

    Note:
        Not thread-safe -- like the underlying :class:`~superdex.physics.Scene`, a
        :class:`~superdex.robotics.Bot` must only be accessed from the thread that
        owns its scene (usually in an async callback if using async scenes.)
    """
    def get_handle(self) -> BotHandle:
        """Handle identifying this bot in its owning
        :class:`~superdex.robotics.RoboticsContext`.

        Returns:
            Handle identifying this bot.
        """
    def get_scene(self) -> Optional[mochi_physics.Scene]:
        """The :class:`~superdex.physics.Scene` in which this bot was created.

        Returns:
            Owning scene, or None if it no longer exists.
        """
    def get_name(self) -> str:
        """Bot name (forwarded from :attr:`~superdex.robotics.BotPrefab.name`).

        Returns:
            Null-terminated bot name.
        """
    def get_bot_prefab(self) -> BotPrefab:
        """The :class:`~superdex.robotics.BotPrefab` from which this bot was created.

        Returns:
            Prefab used to create this bot.
        """
    def get_articulated_actor(self) -> Optional[mochi_physics.Actor]:
        """The underlying articulated :class:`~superdex.physics.Actor` that backs this
        bot
        in the scene.

        Returns:
            Underlying articulated actor, or None if it no longer exists.
        """
    def create_controller(
        self,
        type_name: str,
        name: str = ...,
    ) -> Optional[ControllerBase]:
        """Create a controller of the given type and attach it to this bot.

        Args:
            type_name (str): Registered controller type (e.g., "BASIC_OSC_PD",
                "BASIC_JSC_PD").
            name (str): Instance name for the controller, used by
                :meth:`~superdex.robotics.Bot.find_controllers_by_name`. Names need not
                be unique.

        Returns:
            Pointer to the new controller, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_controller_handles(self) -> DynamicArrayControllerHandle:
        """Get the handles of every controller this bot owns.

        Covers controllers created through
        :meth:`~superdex.robotics.Bot.create_controller` and those created on one of
        this bot's actors with
        :meth:`~superdex.robotics.RoboticsContext.create_controller` — the owning bot is
        inferred from the actor (see
        :meth:`~superdex.robotics.RoboticsContext.get_bot_containing_actor`), so how a
        controller was created makes no difference to whether it appears here. Mirrors
        :meth:`~superdex.robotics.Bot.get_sensor_handles`: the same set the bot-scoped
        finders draw from, and the same set :func:`~superdex.robotics.destroy_bot` tears
        down. Resolve each handle with
        :meth:`~superdex.robotics.RoboticsContext.get_controller`.

        Returns:
            A snapshot of the bot's controller handles, in creation order.
        """
    def get_controller(
        self,
        controller_handle: ControllerHandle,
    ) -> Optional[ControllerBase]:
        """Resolve a controller handle to its underlying
        :class:`~superdex.robotics.ControllerBase`.

        Unlike :meth:`~superdex.robotics.RoboticsContext.get_controller`, which resolves
        any handle in the context, this checks the controller belongs to this bot first
        — so a handle from another bot, or from a standalone actor, is reported as an
        error rather than silently resolved.

        Args:
            controller_handle (ControllerHandle): Handle returned by
                :meth:`~superdex.robotics.Bot.get_controller_handles`.

        Returns:
            Pointer to the controller, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def create_sensor(
        self,
        type_name: str,
        link_name: str,
        name: str = ...,
        param_args: str = ...,
    ) -> Optional[SensorBase]:
        """Create a sensor of the given type on one of this bot's links.

        The bot-level counterpart to declaring a
        :class:`~superdex.robotics.BotSensorPrefab` in the
        :class:`~superdex.robotics.BotPrefab`, for sensors that are only known at
        runtime. The sensor joins :meth:`~superdex.robotics.Bot.get_sensor_handles` and
        is destroyed with the bot, exactly like an auto-instantiated one.

        Args:
            type_name (str): Registered sensor type (e.g. "SENSOR_CAMERA").
            link_name (str): Name of the link (from
                :attr:`~superdex.robotics.BotPrefab.links`) to attach the sensor to.
            name (str): Instance name, used by
                :meth:`~superdex.robotics.Bot.find_sensors_by_name`. Names need not be
                unique.
            param_args (str): Optional params file path or inline JSON; empty uses
                defaults.

        Returns:
            Pointer to the new sensor, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_sensor_handles(self) -> DynamicArraySensorHandle:
        """Get the handles of every sensor this bot owns.

        Covers sensors declared per link in the :class:`~superdex.robotics.BotPrefab`
        via :class:`~superdex.robotics.BotSensorPrefab` and instantiated by
        :func:`~superdex.robotics.create_bot`, those added afterwards via
        :meth:`~superdex.robotics.Bot.create_sensor`, and those created straight off one
        of this bot's actors with
        :meth:`~superdex.robotics.RoboticsContext.create_sensor` — the owning bot is
        inferred from the actor (see
        :meth:`~superdex.robotics.RoboticsContext.get_bot_containing_actor`), so how a
        sensor was created makes no difference to whether it appears here. This is the
        same set the bot-scoped finders draw from, and the same set
        :func:`~superdex.robotics.destroy_bot` tears down. Use
        :meth:`~superdex.robotics.RoboticsContext.get_sensor` on each handle to obtain
        the underlying :class:`~superdex.robotics.SensorBase` pointer.

        Returns:
            A snapshot of the bot's sensor handles in creation order: the
            :attr:`~superdex.robotics.BotPrefab.links` entries first (by link, then by
            per-link sensor index), followed by any later additions.
        """
    def get_sensor(self, sensor_handle: SensorHandle) -> Optional[SensorBase]:
        """Resolve a sensor handle to its underlying
        :class:`~superdex.robotics.SensorBase`.

        Args:
            sensor_handle (SensorHandle): Handle returned by
                :meth:`~superdex.robotics.Bot.get_sensor_handles`.

        Returns:
            Pointer to the sensor, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_sensor_link_name(self, sensor_handle: SensorHandle) -> Optional[str]:
        """Get the name of the link to which the sensor is attached.

        Args:
            sensor_handle (SensorHandle): Handle returned by
                :meth:`~superdex.robotics.Bot.get_sensor_handles`.

        Returns:
            Link name, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def create_actuator(
        self,
        type_name: str,
        link_name: str,
        name: str = ...,
        param_args: str = ...,
    ) -> Optional[ActuatorBase]:
        """Create an actuator of the given type on one of this bot's links. The actuator
        counterpart to :meth:`~superdex.robotics.Bot.create_sensor`, for actuators only
        known at runtime rather than declared as a
        :class:`~superdex.robotics.BotActuatorPrefab`. It joins
        :meth:`~superdex.robotics.Bot.get_actuator_handles` and is destroyed with the
        bot.

        Args:
            type_name (str): Registered actuator type.
            link_name (str): Name of the link (from
                :attr:`~superdex.robotics.BotPrefab.links`) to attach the actuator to.
            name (str): Instance name, used by
                :meth:`~superdex.robotics.Bot.find_actuators_by_name`. Names need not be
                unique.
            param_args (str): Optional params file path or inline JSON; empty uses
                defaults.

        Returns:
            Pointer to the new actuator, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_actuator_handles(self) -> DynamicArrayActuatorHandle:
        """Get the handles of every actuator this bot owns — its
        :class:`~superdex.robotics.BotPrefab` link
        :class:`~superdex.robotics.BotActuatorPrefab` entries, any added afterwards via
        :meth:`~superdex.robotics.Bot.create_actuator`, and any created on one of this
        bot's actors through :meth:`~superdex.robotics.RoboticsContext.create_actuator`.
        Destroyed with the bot. Mirrors
        :meth:`~superdex.robotics.Bot.get_sensor_handles` exactly, ordering included.

        Returns:
            A snapshot of the bot's actuator handles in creation order.
        """
    def get_actuator(self, actuator_handle: ActuatorHandle) -> Optional[ActuatorBase]:
        """Resolve an actuator handle to its underlying
        :class:`~superdex.robotics.ActuatorBase`.

        Args:
            actuator_handle (ActuatorHandle): Handle returned by
                :meth:`~superdex.robotics.Bot.get_actuator_handles`.

        Returns:
            Pointer to the actuator, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_actuator_link_name(self, actuator_handle: ActuatorHandle) -> Optional[str]:
        """Get the name of the link to which the actuator is attached.

        Args:
            actuator_handle (ActuatorHandle): Handle returned by
                :meth:`~superdex.robotics.Bot.get_actuator_handles`.

        Returns:
            Link name, or None on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def find_controllers_by_name(self, name: str) -> DynamicArrayControllerHandle:
        """Find controllers owned by this bot whose instance name equals name. Instance
        names are not unique.

        Args:
            name (str): Exact instance name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_controllers_by_type(self, type_name: str) -> DynamicArrayControllerHandle:
        """Find controllers owned by this bot whose registered type name equals
        typeName.

        Args:
            type_name (str): Exact registered type name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_sensors_by_name(self, name: str) -> DynamicArraySensorHandle:
        """Find sensors owned by this bot whose instance name equals name. Instance
        names
        are not unique.

        Args:
            name (str): Exact instance name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_sensors_by_type(self, type_name: str) -> DynamicArraySensorHandle:
        """Find sensors owned by this bot whose registered type name equals typeName.

        Args:
            type_name (str): Exact registered type name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_actuators_by_name(self, name: str) -> DynamicArrayActuatorHandle:
        """Find actuators owned by this bot whose instance name equals name. Instance
        names
        are not unique.

        Args:
            name (str): Exact instance name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """
    def find_actuators_by_type(self, type_name: str) -> DynamicArrayActuatorHandle:
        """Find actuators owned by this bot whose registered type name equals typeName.

        Args:
            type_name (str): Exact registered type name to match.

        Returns:
            Handles of every match in creation order; empty if none.
        """

class ControllerBasicJscPdParams:
    """Joint-space PD controller parameters."""
    @property
    def kp(self) -> mochi_physics.DynamicArrayReal:
        """The position gain [Nm/rad]"""
    @kp.setter
    def kp(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def kd(self) -> mochi_physics.DynamicArrayReal:
        """The position damping gain [Nms/rad]"""
    @kd.setter
    def kd(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def saturation(self) -> mochi_physics.DynamicArrayReal:
        """The saturation magnitude of the controller output for each joint. Values < 0
        are
        interpreted as infinitiy [N or Nm]
        """
    @saturation.setter
    def saturation(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def deadband(self) -> mochi_physics.DynamicArrayReal:
        """The deadband is removed from error towards 0 (limited to 0) before
        multiplying
        by Kp. Damping is always applied regardless of the deadband. The deadband
        results in a force profile about the target like this \\___/ rather than \\/
        """
    @deadband.setter
    def deadband(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        kp: mochi_physics.ArrayLikeReal = ...,
        kd: mochi_physics.ArrayLikeReal = ...,
        saturation: mochi_physics.ArrayLikeReal = ...,
        deadband: mochi_physics.ArrayLikeReal = ...,
    ) -> None: ...
    @staticmethod
    def load_from_file(path: str) -> ControllerBasicJscPdParams:
        """Load controller parameters from a JSON file.

        Args:
            path (str): Path to a .superdex_controller JSON file.

        Returns:
            Loaded parameters, or default-constructed on failure.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def save_to_file(self, path: str) -> None:
        """Save controller parameters to a JSON file.

        Args:
            path (str): Destination file path.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class ControllerBasicJscPdObsv:
    """Observation state — robot state variables read each control step. Fill it with
    GetCurrentObservationsFromMochi to read the live simulation, or populate it
    directly from an external state source (e.g., a real robot).
    """
    @property
    def dof_positions(self) -> mochi_physics.DynamicArrayReal:
        """All DOF positions [rad or m]"""
    @dof_positions.setter
    def dof_positions(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @property
    def dof_velocities(self) -> mochi_physics.DynamicArrayReal:
        """All DOF velocities [rad/s or m/s]"""
    @dof_velocities.setter
    def dof_velocities(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    dt: float
    """Time since the last ComputeOutput call [s]"""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        dof_positions: mochi_physics.ArrayLikeReal = ...,
        dof_velocities: mochi_physics.ArrayLikeReal = ...,
        dt: float = ...,
    ) -> None: ...

class ControllerBasicJscPdTarget:
    """Target setpoint for the controller."""
    @property
    def target_pose(self) -> mochi_physics.DynamicArrayReal:
        """Target joint positions [m or rad]"""
    @target_pose.setter
    def target_pose(self, value: mochi_physics.ArrayLikeReal) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, target_pose: mochi_physics.ArrayLikeReal = ...) -> None: ...

class CameraSensorParams:
    """Parameters for a camera sensor (fixed or wrist-mounted). Loaded from a
    .superdex_sensor JSON file via SReflect. Fields with value 0 mean "use engine
    default".
    """
    name: str
    """Camera name carried in the params, distinct from the sensor's instance name."""
    image_width: int
    """Rendered image width [px]."""
    image_height: int
    """Rendered image height [px]."""
    fov_vertical_deg: float
    """Vertical field of view [deg]."""
    near_clip: float
    """Distance to the near clip plane [m]."""
    far_clip: float
    """Distance to the far clip plane [m]."""
    @property
    def look_at(self) -> mochi_physics.Real3:
        """Look-at target in world space (fixed cameras only)."""
    @look_at.setter
    def look_at(self, value: mochi_physics.Real3Like) -> None: ...
    @property
    def offset_local(self) -> mochi_physics.Real3:
        """Offset from EE frame origin in local coordinates (wrist cameras only)."""
    @offset_local.setter
    def offset_local(self, value: mochi_physics.Real3Like) -> None: ...
    @property
    def forward_axis(self) -> mochi_physics.Real3:
        """Forward direction in EE-local frame (wrist cameras only)."""
    @forward_axis.setter
    def forward_axis(self, value: mochi_physics.Real3Like) -> None: ...
    @property
    def up_axis_local(self) -> mochi_physics.Real3:
        """Up direction in EE-local frame (wrist cameras only)."""
    @up_axis_local.setter
    def up_axis_local(self, value: mochi_physics.Real3Like) -> None: ...
    look_distance: float
    """Distance ahead of offset point to place look-at target (wrist cameras only)."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        name: str = ...,
        image_width: int = ...,
        image_height: int = ...,
        fov_vertical_deg: float = ...,
        near_clip: float = ...,
        far_clip: float = ...,
        look_at: mochi_physics.Real3Like = ...,
        offset_local: mochi_physics.Real3Like = ...,
        forward_axis: mochi_physics.Real3Like = ...,
        up_axis_local: mochi_physics.Real3Like = ...,
        look_distance: float = ...,
    ) -> None: ...
    @staticmethod
    def load_from_file(path: str) -> CameraSensorParams:
        """Load sensor parameters from a JSON file.

        Args:
            path (str): Path to a .superdex_sensor JSON file.

        Returns:
            Loaded parameters.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def save_to_file(self, path: str) -> None:
        """Save sensor parameters to a JSON file.

        Args:
            path (str): Destination file path.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class ControllerBasicJscPd(ControllerBase):
    """A simple PD controller written in joint space."""
    @staticmethod
    def type_name() -> str:
        """Registration type name for this controller (see
        RoboticsContext::RegisterControllerType).

        Returns:
            This controller's registration type name.
        """
    def get_params(self) -> ControllerBasicJscPdParams:
        """Get controller parameters.

        Returns:
            Reference to parameters.
        """
    def set_params(self, params: ControllerBasicJscPdParams) -> None:
        """Set controller parameters.

        Args:
            params (ControllerBasicJscPdParams): New parameters.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def get_current_observations_from_mochi(self) -> ControllerBasicJscPdObsv:
        """Read current robot state from the Mochi actor.

        Returns:
            Observation struct populated from the actor's current state.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """
    def compute_output(
        self,
        obsv: ControllerBasicJscPdObsv,
        target: ControllerBasicJscPdTarget,
    ) -> mochi_physics.SpanConstReal:
        """Compute PD control efforts from observation state and target setpoint.

        Args:
            obsv (ControllerBasicJscPdObsv): Current robot state (positions, velocities,
                dt).
            target (ControllerBasicJscPdTarget): Target setpoint.

        Returns:
            Efforts for all DOFs [N or Nm]. Returns empty span on error.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

class SensorBase(ComponentBase):
    """Base class for robot sensors. Derives from ComponentBase for common lifecycle
    (validity, actor, destroy). Each derived sensor keeps its own specialized
    ComputeSignal signature.
    """
    def get_parent_from_sensor(self) -> mochi_physics.TransformRT:
        """The sensor's pose relative to its parent frame: the associated link's actor
        for
        bot-owned sensors, or the scene root for scene-level / actor-less sensors.
        aFromB convention (maps sensor-frame coordinates into the parent frame).

        Returns:
            Sensor pose relative to its parent frame.
        """
    def set_parent_from_sensor(
        self,
        parent_from_sensor: mochi_physics.TransformRT,
    ) -> None:
        """Set the sensor's pose relative to its parent frame.

        Args:
            parent_from_sensor (TransformRT): The new parent-from-sensor transform
                (aFromB convention).
        """
    def get_world_transform(self) -> mochi_physics.TransformRT:
        """The sensor's pose in world space. When the sensor is bound to a Mochi
        :class:`~superdex.physics.Actor`, that actor's transform is already
        world-resolved by the simulation, so world = actorWorldTransform *
        parentFromSensor. When the sensor has no actor (a fusion sensor that consumes
        other sensors, or a scene sensor standing in for a scene root that has no Mochi
        actor), the scene root is the parent: world = parentFromSensor, i.e. the
        scene-root-to-world transform is treated as identity (a surrogate for a real
        scene-root actor) until scene spawn transforms are supported.

        Returns:
            Sensor pose in world space.
        """

class ActuatorBase(ComponentBase):
    """Base class for robot actuators.

    Mirrors :class:`~superdex.robotics.ControllerBase` and
    :class:`~superdex.robotics.SensorBase`: derives from ComponentBase for common
    lifecycle (validity, actor, destroy). No concrete actuators exist yet; this
    establishes the contract early so the first actuator follows the same shape as
    controllers and sensors.

    Registration contract (a ``RoboticsContext::RegisterActuator<T>`` template lands
    with the first concrete actuator, mirroring RegisterController/RegisterSensor):
    every actuator must declare static constexpr std::string_view TypeName() {
    return "..."; } (used by the registration templates and for the generated Python
    type_name() binding), implement std::string_view GetTypeName() const override;
    // returns TypeName() and provide a uniform constructor ActuatorX(Actor* actor,
    std::string_view paramArgs, Error& error); that loads its own params from the
    path or inline JSON. An (Actor*, Params const&, Error&) overload is recommended
    for programmatic / non-filesystem construction.

    Teardown contract (mirrors :class:`~superdex.robotics.ControllerBase` /
    :class:`~superdex.robotics.SensorBase`):
    :meth:`~superdex.robotics.ComponentBase.get_actor` resolves the live actor on
    demand and yields None once the owning mochi Scene (or the actor) is gone, so an
    actuator that outlives its Scene (Scene destroyed before the RoboticsContext)
    sees :meth:`~superdex.robotics.ComponentBase.get_actor` == None in its
    destructor. Any concrete actuator whose destructor releases actor-held resources
    must therefore guard on GetActor() != None (or, for context-owned resources,
    resolve via GetContext()) so teardown never dereferences a dangling Actor*.
    """
    ...

class CameraSensor(SensorBase):
    """Camera sensor runtime object. Stores intrinsics/extrinsics for use by renderers
    (UE, etc.). No ComputeSignal — cameras don't produce data in the mochi physics
    loop; renderers query GetParams() to configure their camera actors.
    """
    @staticmethod
    def type_name() -> str:
        """Registration type name for this sensor (see
        RoboticsContext::RegisterSensorType).

        Returns:
            This sensor's registration type name.
        """
    def get_params(self) -> CameraSensorParams:
        """Get sensor parameters.

        Returns:
            The params.
        """
    def set_params(self, params: CameraSensorParams) -> None:
        """Set sensor parameters.

        Args:
            params (CameraSensorParams): Params.

        Raises:
            :class:`~superdex.physics.Error`: If an error occurs.
        """

EFFORT_UNBOUNDED: float
"""Sentinel :attr:`~superdex.robotics.BotJointPrefab.effort_limit` value: the
joint's actuation effort is unbounded.
"""

def load_bot_prefab_from_file(path: str) -> BotPrefab:
    """Load bot parameters from a .superdex_bot file using the default file-based
    loader. Automatically resolves ModBotPrefab files by building the final
    :class:`~superdex.robotics.BotPrefab`.

    If path is a .superdex_bot_archive file (see ArchiveBot), the archive is
    transparently extracted and cached into a temp directory and the embedded target
    bot is loaded.

    Args:
        path (str): File path to the .superdex_bot or .superdex_bot_archive file.

    Returns:
        Loaded or built :class:`~superdex.robotics.BotPrefab`, or
        default-constructed on failure.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def load_bot_prefab_from_urdf_file(path: str) -> BotPrefab:
    """Load bot parameters from a URDF file.

    Parses the URDF and resolves each link's visual and collision mesh references
    relative to the URDF location (ROS `package://` URIs are supported), storing the
    resolved on-disk paths in the returned prefab. Collision meshes may be any
    format the shape loader accepts (e.g. .stl, .obj, .ply, .off, .mochi.h5); when a
    collision mesh carries no baked SDF, one is generated on demand at bot creation.
    A free `world_joint` is injected at index 0.

    Args:
        path (str): Path to the .urdf file.

    Returns:
        The loaded or built :class:`~superdex.robotics.BotPrefab`.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        Only ``<mesh>`` geometry is imported. Primitive URDF shapes (``<box>``,
        ``<cylinder>``, ``<sphere>``) in ``<visual>`` / ``<collision>`` elements are
        not supported and are silently skipped; the importer uses the first
        mesh-bearing visual/collision on each link.
    """

def build_articulated_pose_from_bot_pose(
    bot_prefab: BotPrefab,
    src_pose: mochi_physics.ArrayLikeReal,
    num_actor_dofs: int,
) -> mochi_physics.DynamicArrayReal:
    """Convert a bot-space pose to an articulated-actor pose.

    Bot DOFs never include the root joint's, whether or not the articulation has
    any: a Free root contributes 6 actor DOFs that bot space excludes, and a Hard
    root contributes none. The two spaces therefore share an order and differ only
    by that leading offset, so this copies srcPose to pose[i + numBaseDofs] and
    zero-fills the base DOFs, producing the actor-DOF layout
    :meth:`~superdex.physics.Actor.set_articulated_pose_from_joints` expects. It
    never permutes.

    Args:
        bot_prefab (BotPrefab): Bot describing the articulation.
        src_pose (ArrayLikeReal): Bot-space pose (must have
            ``superdex::robotics::BotPrefab::_numDofs`` entries).
        num_actor_dofs (int): The actor's DOF count
            (:meth:`~superdex.physics.Actor.get_num_dofs`).

    Returns:
        Pose in actor-DOF layout, sized to numActorDofs.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Warning:
        This documentation references the following C++ API, which is not available
        in Python: ``superdex::robotics::BotPrefab::_numDofs``.
    """

def create_bot(
    scene: mochi_physics.Scene,
    bot_prefab: BotPrefab,
    bots_context: RoboticsContext,
) -> Optional[Bot]:
    """Create a :class:`~superdex.robotics.Bot` runtime object from a
    :class:`~superdex.robotics.BotPrefab`. Builds the underlying articulated actor
    in scene and seeds its default pose. The returned
    :class:`~superdex.robotics.Bot` owns no scene resources beyond the actor —
    destroy it with :func:`~superdex.robotics.destroy_bot`. This must be in the
    scene thread (i.e. in an async callback if using async scenes.)

    Args:
        scene (Scene): Target scene in which to create the bot and its components.
        bot_prefab (BotPrefab): Bot parameters describing the articulation.
        bots_context (RoboticsContext): Bots context used for components created on
            the bot. Must outlive the returned :class:`~superdex.robotics.Bot`.

    Returns:
        Pointer to the created :class:`~superdex.robotics.Bot`.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def destroy_bot(scene: mochi_physics.Scene, bot: Optional[Bot]) -> None:
    """Destroy a :class:`~superdex.robotics.Bot` previously created by
    :func:`~superdex.robotics.create_bot`. Destroys the underlying articulated actor
    in its owning scene and any controllers, sensors, and actuators the bot created.
    This must be in the scene thread (i.e. in an async callback if using async
    scenes.)

    Args:
        scene (Scene): Scene to remove the bot from. Must be the same scene used to
            create the bot.
        bot (Optional[Bot]): Pointer to the bot to be destroyed.
    """

def create_context() -> RoboticsContext: ...
