/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <mochi_core/geometry/bvh_tree.h>
#include <mochi_core/geometry/geometry_utils.h>
#include <mochi_core/geometry/tetrahedral_mesh.h>
#include <mochi_core/geometry/triangular_mesh.h>
#include <mochi_core/utils/profile.h>
#include <mochi_core/utils/task_scheduler.h>

#include <algorithm>
#include <cmath>
#include <iterator>
#include <memory>
#include <numeric>
#include <vector>

namespace mochi {

/*************************************************************************************************/

namespace {
template <typename Bv>
struct BvhPartition {
  // Index of the splitting entry in the element index span, effectively partitioning the n elements
  // into two independent sets [0, splittingIndex) and [splittingIndex, n).
  int splittingIndex = 0;
  // The merged bounding volume of all entries. Generated by top-down partition algorithms.
  Bv bv;
  // The left partition bounding volume. Generated by bottom-up partition algorithms.
  Bv leftBv;
  // The right partition bounding volume. Generated by bottom-up partition algorithms.
  Bv rightBv;
};
} // namespace

/*************************************************************************************************/

/**
 * Simple algorithm top-down algorithm. Given the function W(𝕊) = ∑ᵢw(𝕊ᵢ) that
 * computes the weighted sum of the objects in set 𝕊, the algorithm greedily tries to split
 * into two sets 𝕊ᵢ, 𝕊ⱼ such that W(𝕊ᵢ) ≈ W(𝕊ⱼ). Loosely related to KD-Tree splitting.
 * The weight w() may be the surface area of the BV, or 1 (needed for BVHs of point sets)
 */
template <typename Bv>
static BvhPartition<Bv> Partition_TopDown_Mean(
    BvhObject<Bv> const* object,
    Span<int> elementIndicesSpan,
    bool useAreaWeighting) {
  // Estimate weighted mean and aggregate AABB.
  // If `useAreaWeighting` is enabled, use surface-area weighting, otherwise uniform weighting.
  auto bv = GetAabb(object->GetBv(elementIndicesSpan[0]));
  real weight = useAreaWeighting ? CalcShapeSurfaceArea(bv) : 1_r;
  Vec4r centroid = bv.VGetCenter() * weight;

  for (size_t i = 1; i < elementIndicesSpan.size(); ++i) {
    // Retrieve the element's AABB, accumulate centroid.
    auto const elementBv = GetAabb(object->GetBv(elementIndicesSpan[i]));
    auto const thisWeight = useAreaWeighting ? CalcShapeSurfaceArea(elementBv) : 1_r;
    centroid += elementBv.VGetCenter() * thisWeight;
    weight += thisWeight;

    // Update merged AABB.
    bv = EncloseShapes(bv, elementBv);
  }
  centroid /= weight;

  // Estimate maximum spread direction from aggregate AABB.
  auto maxSpreadDirection = GetMaxSpreadDirection(bv);
  auto distanceToCentroid = Dot<3>(maxSpreadDirection, centroid);

  // Partition elements according to this.
  // NOTE: Capturing distanceToCentroid and maxSpreadDirection by reference to avoid alignment
  // warning in MSVC2017.
  auto mid = std::partition(
      elementIndicesSpan.begin(),
      elementIndicesSpan.end(),
      [&distanceToCentroid, &maxSpreadDirection, object](int i) {
        auto const& elementCenter = object->GetBv(i).VGetCenter();
        auto distanceToCenter = Dot<3>(maxSpreadDirection, elementCenter);
        return distanceToCenter < distanceToCentroid;
      });

  // If the resulting split is invalid, the element set might be degenerated.
  // In such cases, opt to split the elements into two halves regardless of where they are located.
  size_t const numLeftElements = std::distance(elementIndicesSpan.begin(), mid);
  size_t const numRightElements = elementIndicesSpan.size() - numLeftElements;

  if (numLeftElements == 0 || numRightElements == 0) {
    mid = elementIndicesSpan.begin() + ((numLeftElements + numRightElements) / 2);
  }

  // Done!
  BvhPartition<Bv> partition;
  partition.splittingIndex = (int)std::distance(elementIndicesSpan.begin(), mid);
  GetBoundingVolume(bv, partition.bv);
  return partition;
}

/*************************************************************************************************/

template <typename Bv>
static Bv EncloseShapes(BvhObject<Bv> const* object, Span<int> const& span) {
  Bv bv = object->GetBv(span[0]);

  for (size_t i = 1; i < span.size(); ++i) {
    auto const elementBv = object->GetBv(span[i]);
    bv = EncloseShapes(bv, elementBv);
  }

  return bv;
}

/*************************************************************************************************/

template <typename Bv>
BvhTree<Bv>::BvhTree(BvhObject<Bv> const* object, BvhTreeParams const& params) {
  MOCHI_PROFILE_SCOPE();
  MOCHI_ASSERT(object, "Invalid BVH object supplied");
  MOCHI_ASSERT(object->GetNumElements() > 0, "Cannot build BVH tree from empty object.");
  MOCHI_ASSERT(
      (dynamic_cast<PointSetBvhObject<Bv> const*>(object) == nullptr) ||
          (params.splittingAlgorithm != BvhSplittingAlgorithm::TopDown_AreaWeightedMean),
      "PointSetBvhObject does not support area-weighted splitting. Use BvhSplitting::AlgorithmTopDown_Mean instead.");
  _object = object;
  _params = params;

  // Preallocate node levels. Since we don't know the exact number in advance, pre-allocate
  // according to the maximum number of levels as prescribed by the parameters. We need this for
  // keeping track of what nodes constitute a depth level (so we can parallelize the fitting
  // procedure).
  _levels.resize(_params.maxDepthPerBranch);

  // Initialize element partition in no particular order. Then, start build procedure from root
  // node. NOTE@Hector: We only support top-down building as of now. If this proves to be
  // insufficient (e.g., because of the quality of the tree) then we will need to modify all this.
  _elements.resize(_object->GetNumElements());
  std::iota(_elements.begin(), _elements.end(), 0);
  BuildNode(kInvalidIndex, MakeSpan(_elements), /*depth*/ 0);

  // Once built, deallocate extra memory by shrinking buffers. This step will also remove empty
  // levels, thus making the levels vector be of the same size as the maximum depth reached.
  ShrinkBuffers();
}

template <typename Bv>
bool BvhTree<Bv>::IsValid() const {
  return _object && _object->GetNumElements() == _elements.size();
}

template <typename Bv>
BvhObject<Bv> const* BvhTree<Bv>::GetObject() const {
  return _object;
}

template <typename Bv>
BvhTreeParams const& BvhTree<Bv>::GetParams() const {
  return _params;
}

template <typename Bv>
Bv const& BvhTree<Bv>::GetRootBv() const {
  MOCHI_ASSERT_VERBOSE(IsValid(), "Invalid BVH Tree");
  return _nodes[kRootNode].bv;
}

template <typename Bv>
void BvhTree<Bv>::Refit() {
  MOCHI_PROFILE_SCOPE();
  MOCHI_ASSERT_VERBOSE(IsValid(), "Invalid BVH Tree");

  // Refit entries in parallel bottom-up.
  for (int i = isize(_levels) - 1; i >= 0; --i) {
    ParallelForEach("RefitNode", _levels[i], _params.refitGranularity, [this](auto& entry) {
      RefitNode(entry);
    });
  }
}

template <typename Bv>
void BvhTree<Bv>::Query(Bv const& bv, BvhQueryFn const& callback) const {
  MOCHI_ASSERT_VERBOSE(IsValid(), "Invalid BVH Tree");
  QueryNode(bv, kRootNode, callback);
}

template <typename Bv>
void BvhTree<Bv>::Intersect(BvhTree const& other, BvhIntersectionQueryFn const& callback) const {
  MOCHI_ASSERT_VERBOSE(IsValid(), "Invalid BVH Tree");
  MOCHI_ASSERT_VERBOSE(other.IsValid(), "Invalid BVH Tree");
  MOCHI_ASSERT_VERBOSE(&other != this, "BvhTree::Intersect does not support self-intersection.");

  IntersectNodes(other, kRootNode, kRootNode, callback);
}

template <typename Bv>
int BvhTree<Bv>::FindClosest(Real3 const& queryPoint, real* outDistanceSqr) const {
  return VFindClosest(ToSimd(queryPoint), outDistanceSqr);
}

template <typename Bv>
int BvhTree<Bv>::VFindClosest(Vec4r queryPoint, real* outDistanceSqr) const {
  MOCHI_ASSERT_VERBOSE(IsValid(), "Invalid BVH Tree");

  // Initialize candidate to arbitrary entry.
  int bestIndex = 0;
  real bestDistanceSqr = Get0(_object->VGetDistanceSqr(queryPoint, 0));

  // Traverse tree.
  FindClosestOnNode(kRootNode, queryPoint, bestIndex, bestDistanceSqr);

  // Finally, output results.
  if (outDistanceSqr) {
    *outDistanceSqr = bestDistanceSqr;
  }
  return bestIndex;
}

template <typename Bv>
size_t BvhTree<Bv>::GetNodeCount() const {
  return _nodes.size();
}

template <typename Bv>
RangeByIterators<std::vector<int>::const_iterator> BvhTree<Bv>::GetElements(
    Node const& node) const {
  return _elements.begin() + node.elementIndexRange;
}

template <typename Bv>
int BvhTree<Bv>::BuildNode(int parentIndex, Span<int> elementIndicesSpan, int depth) {
  MOCHI_PROFILE_SCOPE();

  // Fetch new node index.
  int nodeIndex = isize(_nodes);

  // Generate node and setup common terms.
  _nodes.emplace_back();
  _nodes[nodeIndex].parentIndex = parentIndex;
  _nodes[nodeIndex].elementIndexRange = {
      (int)std::distance(_elements.data(), elementIndicesSpan.begin()),
      (int)std::distance(_elements.data(), elementIndicesSpan.end())};
  _levels[depth].push_back(nodeIndex);

  // If maximum recursion has been reached, build leaf node.
  bool const reachedMaxElements = elementIndicesSpan.size() > _params.maxElementsPerLeaf;
  bool const reachedMaximumDepth = (depth + 1) >= _params.maxDepthPerBranch;
  if (!reachedMaxElements || reachedMaximumDepth) {
    _nodes[nodeIndex].isLeafNode = true;
    _nodes[nodeIndex].bv = EncloseShapes(_object, elementIndicesSpan);
    _leaves.push_back(nodeIndex);

    // Ensure local ordering of the elements.
    std::sort(elementIndicesSpan.begin(), elementIndicesSpan.end());
  }

  // Otherwise, determine split and generate branch nodes.
  else {
    // Partition elements according to the selected heuristic.
    // NOTE@Hector: We only have two heuristics at the moment, generalize if necessary.
    auto partition = Partition_TopDown_Mean(
        _object,
        elementIndicesSpan,
        _params.splittingAlgorithm == BvhSplittingAlgorithm::TopDown_AreaWeightedMean);
    auto splittingPoint = elementIndicesSpan.begin() + partition.splittingIndex;
    int numLeftElementIndices = (int)std::distance(elementIndicesSpan.begin(), splittingPoint);
    int numRightElementIndices = (int)std::distance(splittingPoint, elementIndicesSpan.end());

    // Recursively build children.
    auto leftElementIndicesSpan = Span<int>(elementIndicesSpan.begin(), numLeftElementIndices);
    auto rightElementIndicesSpan = Span<int>(splittingPoint, numRightElementIndices);
    _nodes[nodeIndex].bv = partition.bv;
    _nodes[nodeIndex].leftChildIndex = BuildNode(nodeIndex, leftElementIndicesSpan, depth + 1);
    _nodes[nodeIndex].rightChildIndex = BuildNode(nodeIndex, rightElementIndicesSpan, depth + 1);
  }

  // Done!
  return nodeIndex;
}

template <typename Bv>
Bv BvhTree<Bv>::ComputeNodeBv(int index) const {
  auto& node = _nodes[index];
  auto bv = _object->GetBv(_elements[node.elementIndexRange.Min()]);

  auto elemRange = _elements.begin() + node.elementIndexRange;
  for (auto&& e : elemRange) {
    bv = EncloseShapes(bv, _object->GetBv(e));
  }
  return bv;
}

template <typename Bv>
void BvhTree<Bv>::RefitNode(int nodeIndex) {
  auto& node = _nodes[nodeIndex];

  // Refit leaf node.
  if (node.isLeafNode) {
    node.bv = ComputeNodeBv(nodeIndex);
  }
  // Refit interior node.
  else {
    auto const& leftChildNode = _nodes[node.leftChildIndex];
    auto const& rightChildNode = _nodes[node.rightChildIndex];
    node.bv = EncloseShapes(leftChildNode.bv, rightChildNode.bv);
  }
}

template <typename Bv>
void BvhTree<Bv>::QueryNode(Bv const& bv, int nodeIndex, BvhQueryFn const& callback) const {
  auto const& node = _nodes[nodeIndex];

  // If the input bounding volume overlaps the node, proceed.
  if (HasOverlap(bv, node.bv)) {
    // If the leaf node has been reached, test individual leaves and invoke the callback on
    // all the potentially intersecting ones.
    if (node.isLeafNode) {
      auto elemRange = _elements.begin() + node.elementIndexRange;

      for (auto&& e : elemRange) {
        if (HasOverlap(bv, _object->GetBv(e))) {
          callback(e);
        }
      }
    }
    // Otherwise, traverse children.
    else {
      QueryNode(bv, node.leftChildIndex, callback);
      QueryNode(bv, node.rightChildIndex, callback);
    }
  }
}

template <typename Bv>
void BvhTree<Bv>::IntersectNodes(
    BvhTree const& other,
    int thisIndex,
    int otherIndex,
    BvhIntersectionQueryFn const& callback) const {
  MOCHI_PROFILE_SCOPE();
  auto const& thisNode = _nodes[thisIndex];
  auto const& otherNode = other._nodes[otherIndex];

  if (HasOverlap(thisNode.bv, otherNode.bv)) {
    // If both nodes are leaves, test individual entries and determine which are
    // potentially overlapping. Invoke the callback for each overlapping pair.
    if (thisNode.isLeafNode && otherNode.isLeafNode) {
      auto thisRange = _elements.begin() + thisNode.elementIndexRange;
      auto otherRange = other._elements.begin() + otherNode.elementIndexRange;

      for (auto thisE : thisRange) {
        auto thisBv = _object->GetBv(thisE);

        for (auto otherE : otherRange) {
          auto otherBv = other._object->GetBv(otherE);
          if (HasOverlap(thisBv, otherBv)) {
            callback(thisE, otherE);
          }
        }
      }
    }
    // Otherwise, traverse children by recursing over the different branches.
    else if (thisNode.isLeafNode) {
      IntersectNodes(other, thisIndex, otherNode.leftChildIndex, callback);
      IntersectNodes(other, thisIndex, otherNode.rightChildIndex, callback);
    } else if (otherNode.isLeafNode) {
      IntersectNodes(other, thisNode.leftChildIndex, otherIndex, callback);
      IntersectNodes(other, thisNode.rightChildIndex, otherIndex, callback);
    } else {
      IntersectNodes(other, thisNode.leftChildIndex, otherNode.leftChildIndex, callback);
      IntersectNodes(other, thisNode.leftChildIndex, otherNode.rightChildIndex, callback);
      IntersectNodes(other, thisNode.rightChildIndex, otherNode.leftChildIndex, callback);
      IntersectNodes(other, thisNode.rightChildIndex, otherNode.rightChildIndex, callback);
    }
  }
}

template <typename Bv>
void BvhTree<Bv>::FindClosestOnNode(
    int nodeIndex,
    Vec4r point,
    int& bestIndex,
    real& bestDistanceSqr) const {
  auto const& node = _nodes[nodeIndex];

  // Find distance from query point to the BV. If closer than current best candidate, traverse.
  real volumeDistanceSqr = Get0(VDistancePointShapeSqr(point, node.bv));
  if (volumeDistanceSqr < bestDistanceSqr) {
    // Test distance to elements.
    if (node.isLeafNode) {
      auto elemRange = Slice(_elements, node.elementIndexRange);
      for (auto&& elem : elemRange) {
        real distanceSqr = Get0(_object->VGetDistanceSqr(point, elem));
        if (distanceSqr < bestDistanceSqr) {
          bestIndex = elem;
          bestDistanceSqr = distanceSqr;
        }
      }
    }
    // Test distance to children.
    else {
      FindClosestOnNode(node.leftChildIndex, point, bestIndex, bestDistanceSqr);
      FindClosestOnNode(node.rightChildIndex, point, bestIndex, bestDistanceSqr);
    }
  }
}

template <typename Bv>
void BvhTree<Bv>::ShrinkBuffers() {
  MOCHI_PROFILE_SCOPE();

  // Prune empty levels if maximum depth was not reached.
  auto it = std::find_if(_levels.begin(), _levels.end(), [](auto& l) { return l.size() == 0; });
  _levels.erase(it, _levels.end());

  // Shrink buffers to reduce wasted memory.
  _nodes.shrink_to_fit();
  _leaves.shrink_to_fit();
  _elements.shrink_to_fit();
  _levels.shrink_to_fit();
  for (auto& l : _levels) {
    l.shrink_to_fit();
  }
}

template class BvhTree<Aabb>;
template class BvhTree<Sphere>;

/*************************************************************************************************/

static void GetTriangleBv(Vec4r A, Vec4r B, Vec4r C, Aabb& outBv) {
  Vec4r minCoord = Min(A, B, C);
  Vec4r maxCoord = Max(A, B, C);
  outBv = Aabb{minCoord, maxCoord};
}

static void GetTetrahedronBv(Vec4r A, Vec4r B, Vec4r C, Vec4r D, Aabb& outBv) {
  Vec4r minCoord = Min(A, B, C, D);
  Vec4r maxCoord = Max(A, B, C, D);
  outBv = Aabb{minCoord, maxCoord};
}

static void GetPointBv(Real3 p, Aabb& outBv) {
  outBv = Aabb{p, p};
}

static void GetPointBv(Real3 p, Sphere& outBv) {
  outBv = Sphere{p, 0_r};
}

/*************************************************************************************************/

template <typename Bv>
TriangularMeshBvhObject<Bv>::TriangularMeshBvhObject(
    std::shared_ptr<TriangularMesh const> const& mesh,
    Span<Real3 const> coordinates) {
  Initialize(mesh, coordinates);
}

template <typename Bv>
void TriangularMeshBvhObject<Bv>::Initialize(
    std::shared_ptr<TriangularMesh const> const& mesh,
    Span<Real3 const> coordinates) {
  MOCHI_PROFILE_SCOPE();
  MOCHI_ASSERT(mesh != nullptr, "Invalid mesh pointer");
  MOCHI_ASSERT(!coordinates || coordinates.size() == mesh->GetNumNodes(), "Invalid coordinates");
  _mesh = mesh;
  _coordinates = coordinates ? coordinates : _mesh->GetNodeCoordinates();
}

template <typename Bv>
bool TriangularMeshBvhObject<Bv>::IsInitialized() const {
  return _mesh != nullptr;
}

template <typename Bv>
int TriangularMeshBvhObject<Bv>::GetNumElements() const {
  return _mesh->GetNumFaces();
}

template <typename Bv>
Bv TriangularMeshBvhObject<Bv>::GetBv(int index) const {
  MOCHI_ASSERT_VERBOSE(index >= 0 && index < _mesh->GetNumFaces(), "Invalid face index");

  Int3 const face = _mesh->GetElementConnectivity()[index];
  Vec4r A = ToSimd(_coordinates[face[0]]);
  Vec4r B = ToSimd(_coordinates[face[1]]);
  Vec4r C = ToSimd(_coordinates[face[2]]);

  Bv outBv;
  GetTriangleBv(A, B, C, outBv);
  return outBv;
}

template <typename Bv>
real TriangularMeshBvhObject<Bv>::GetDistanceSqr(Real3 const& point, int index) const {
  return Get0(VGetDistanceSqr(ToSimd(point), index));
}

template <typename Bv>
Vec4r TriangularMeshBvhObject<Bv>::VGetDistanceSqr(Vec4r point, int index) const {
  MOCHI_ASSERT_VERBOSE(index >= 0 && index < _mesh->GetNumFaces(), "Invalid face index");

  Int3 const face = _mesh->GetElementConnectivity()[index];
  Vec4r A = ToSimd(_coordinates[face[0]]);
  Vec4r B = ToSimd(_coordinates[face[1]]);
  Vec4r C = ToSimd(_coordinates[face[2]]);
  VDistanceSignParams unused;
  return VDistancePointTriangleSqr(point, A, B, C, unused);
}

template class TriangularMeshBvhObject<Aabb>;

template <typename Bv>
TetrahedralMeshBvhObject<Bv>::TetrahedralMeshBvhObject(
    std::shared_ptr<TetrahedralMesh const> const& mesh,
    Span<Real3 const> coordinates) {
  Initialize(mesh, coordinates);
}

template <typename Bv>
void TetrahedralMeshBvhObject<Bv>::Initialize(
    std::shared_ptr<TetrahedralMesh const> const& mesh,
    Span<Real3 const> coordinates) {
  MOCHI_PROFILE_SCOPE();
  MOCHI_ASSERT(mesh != nullptr, "Invalid mesh pointer");
  MOCHI_ASSERT(!coordinates || coordinates.size() == mesh->GetNumNodes(), "Invalid coordinates");
  _mesh = mesh;
  _coordinates = coordinates ? coordinates : _mesh->GetNodeCoordinates();
}

template <typename Bv>
bool TetrahedralMeshBvhObject<Bv>::IsInitialized() const {
  return _mesh != nullptr;
}

template <typename Bv>
int TetrahedralMeshBvhObject<Bv>::GetNumElements() const {
  return _mesh->GetNumElements();
}

template <typename Bv>
Bv TetrahedralMeshBvhObject<Bv>::GetBv(int index) const {
  MOCHI_ASSERT_VERBOSE(index >= 0 && index < _mesh->GetNumElements(), "Invalid element index");

  Int4 const tet = _mesh->GetElementConnectivity()[index];
  Vec4r A = ToSimd(_coordinates[tet[0]]);
  Vec4r B = ToSimd(_coordinates[tet[1]]);
  Vec4r C = ToSimd(_coordinates[tet[2]]);
  Vec4r D = ToSimd(_coordinates[tet[3]]);

  Bv outBv;
  GetTetrahedronBv(A, B, C, D, outBv);
  return outBv;
}

template <typename Bv>
real TetrahedralMeshBvhObject<Bv>::GetDistanceSqr(Real3 const& point, int index) const {
  return Get0(VGetDistanceSqr(ToSimd(point), index));
}

template <typename Bv>
Vec4r TetrahedralMeshBvhObject<Bv>::VGetDistanceSqr(Vec4r point, int index) const {
  MOCHI_ASSERT_VERBOSE(index >= 0 && index < _mesh->GetNumElements(), "Invalid element index");

  Int4 const tet = _mesh->GetElementConnectivity()[index];
  Vec4r A = ToSimd(_coordinates[tet[0]]);
  Vec4r B = ToSimd(_coordinates[tet[1]]);
  Vec4r C = ToSimd(_coordinates[tet[2]]);
  Vec4r D = ToSimd(_coordinates[tet[3]]);
  return VDistancePointTetrahedronSqr(point, A, B, C, D);
}

template class TetrahedralMeshBvhObject<Aabb>;

template <typename Bv>
Bv PointSetBvhObject<Bv>::GetBv(int index) const {
  MOCHI_ASSERT_VERBOSE(index >= 0 && index < _points.size(), "Invalid element index");

  Bv outBv;
  GetPointBv(_points[index], outBv);
  return outBv;
}

template <typename Bv>
real PointSetBvhObject<Bv>::GetDistanceSqr(Real3 const& point, int index) const {
  return Get0(VGetDistanceSqr(ToSimd(point), index));
}

template <typename Bv>
Vec4r PointSetBvhObject<Bv>::VGetDistanceSqr(Vec4r point, int index) const {
  MOCHI_ASSERT_VERBOSE(index >= 0 && index < _points.size(), "Invalid element index");

  return VNormSqr<3>(point - ToSimd(_points[index]));
}

template class PointSetBvhObject<Aabb>;
template class PointSetBvhObject<Sphere>;

/*************************************************************************************************/

} // namespace mochi
