/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useEffect, useRef } from 'react';
import { useColorMode } from '@docusaurus/theme-common';
import useBaseUrl from '@docusaurus/useBaseUrl';

/**
 * An iframe hosting the generated API reference (Doxygen for C++, Sphinx for
 * Python).
 *
 * Theming is baked into the generated pages themselves: each page's <head> has
 * a synchronous script that applies the light/dark class from localStorage
 * before first paint, plus a render-blocking <link> to the shared theme
 * stylesheet (static/api-embed.css). So every page — the initial load and every
 * in-frame navigation — paints already themed. There is deliberately NO
 * hide/reveal or runtime stylesheet injection here: those produced either a
 * flash of the stock Doxygen/Sphinx theme or, when we hid the frame to avoid it,
 * a blank content gap on each click. Keeping the frame always visible with the
 * theme baked in is what makes navigation smooth.
 *
 * This component only:
 *   - pushes live theme toggles from the parent into the frame via postMessage,
 *   - fills the otherwise-blank Doxygen landing page with a section list,
 *   - opens external / raw-source links in a new tab, and
 *   - keeps Doxygen's frame-escaping search-result links inside the iframe.
 */
export default function APIFrame({ src, title, style, ...props }) {
  const iframeRef = useRef(null);
  const { colorMode } = useColorMode();
  const resolvedSrc = useBaseUrl(src);

  useEffect(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;

    const unloadCleanups = [];

    // Push the current theme to the (baked-in) child theme handler.
    const sendThemeToIframe = () => {
      if (iframe.contentWindow) {
        iframe.contentWindow.postMessage(
          { type: 'setTheme', theme: colorMode },
          '*'
        );
      }
    };

    // The Doxygen C++ landing page (index.html) has no @mainpage content, so its
    // content area is blank. Fill it with a top-level section list for a better
    // first impression. Best-effort and idempotent; survives doc regeneration.
    const maybeInjectCppLanding = (doc) => {
      try {
        if (!doc.getElementById('projectname')) return; // Doxygen only
        const path = (doc.location && doc.location.pathname) || '';
        if (!/\/(index\.html)?$/.test(path)) return; // main page only
        const contents = doc.querySelector('div.contents');
        if (!contents || doc.getElementById('superdex-robotics-api-landing')) return;
        if (contents.textContent.trim().length > 0) return; // already has content

        const sections = [
          ['namespaces.html', 'Namespaces', 'All namespaces and their members'],
          ['annotated.html', 'Classes', 'Class list with descriptions'],
          ['hierarchy.html', 'Class Hierarchy', 'Inheritance relationships'],
          ['files.html', 'Files', 'Header and source file index'],
        ];
        const wrap = doc.createElement('div');
        wrap.id = 'superdex-robotics-api-landing';
        wrap.innerHTML =
          '<p class="superdex-robotics-api-landing-lead">' +
          'Browse by namespace, class, hierarchy, or file.</p>' +
          '<div class="superdex-robotics-api-landing-grid">' +
          sections
            .map(
              ([href, title, desc]) =>
                `<a class="superdex-robotics-api-landing-card" href="${href}">` +
                `<span class="superdex-robotics-api-landing-title">${title}</span>` +
                `<span class="superdex-robotics-api-landing-desc">${desc}</span></a>`
            )
            .join('') +
          '</div>';
        contents.appendChild(wrap);
      } catch (e) {
        // best-effort — ignore
      }
    };

    // Make external links (e.g. the "Generated by doxygen" doxygen.org link)
    // open in a new tab instead of loading inside — and hijacking — the iframe.
    const fixExternalLinks = (doc) => {
      try {
        const host = doc.location && doc.location.hostname;
        doc.querySelectorAll('a[href]').forEach((a) => {
          const href = a.getAttribute('href') || '';
          // Resolve against the page so protocol-relative (//host/…) and
          // absolute links are both normalized; skip anything that can't be
          // parsed or isn't http(s) (mailto:, #anchors, relative paths).
          let url;
          try {
            url = new URL(href, doc.location.href);
          } catch (e) {
            return;
          }
          if (url.protocol !== 'http:' && url.protocol !== 'https:') return;
          // Raw-source pages (RTD "View page source", _sources/*.txt) are plain
          // text that can't be themed inside the dark iframe and render as
          // unreadable dark-on-dark; open them in a new tab (readable browser
          // default) like external links.
          const rawSource =
            /\/_sources\//.test(url.pathname) || /\.txt$/i.test(url.pathname);
          if (url.hostname !== host || rawSource) {
            a.setAttribute('target', '_blank');
            a.setAttribute('rel', 'noopener noreferrer');
          }
        });
      } catch (e) {
        // best-effort — ignore
      }
    };

    const onLoad = () => {
      let doc;
      try {
        doc = iframe.contentDocument;
      } catch (e) {
        return; // cross-origin — nothing to do
      }
      if (!doc || (doc.location && doc.location.href === 'about:blank')) {
        return;
      }

      maybeInjectCppLanding(doc);
      fixExternalLinks(doc);

      // Doxygen search-result links carry target="_parent" (a relic of its old
      // frameset layout), and results are injected dynamically so they can't be
      // rewritten at load time. Inside this embedding iframe, _parent/_top is the
      // Docusaurus window, so clicking a result would replace the whole site with
      // the raw, unshelled Doxygen page. Intercept clicks on same-origin
      // frame-escaping links (capture phase, before Doxygen's own handlers) and
      // navigate the iframe itself so the site shell survives.
      const win = doc.defaultView;
      if (win && !win.__superdexRoboticsFrameEscapeHooked) {
        win.__superdexRoboticsFrameEscapeHooked = true;
        const onFrameEscapeClick = (e) => {
          const a =
            e.target &&
            e.target.closest &&
            e.target.closest('a[target="_parent"], a[target="_top"]');
          if (!a) return;
          let url;
          try {
            url = new URL(a.getAttribute('href') || '', doc.location.href);
          } catch (err) {
            return;
          }
          if (url.protocol !== 'http:' && url.protocol !== 'https:') return;
          // Leave genuinely external links to fixExternalLinks (new tab).
          if (url.hostname !== (doc.location && doc.location.hostname)) return;
          e.preventDefault();
          win.location.assign(url.href);
        };
        win.addEventListener('click', onFrameEscapeClick, true);
        unloadCleanups.push(() => {
          try {
            win.removeEventListener('click', onFrameEscapeClick, true);
            delete win.__superdexRoboticsFrameEscapeHooked;
          } catch (e) {
            // window may be gone after navigation — ignore.
          }
        });
      }

      // Keep the frame's baked-in theme in sync with the parent (covers the
      // rare case where the parent toggled theme during the child's load).
      sendThemeToIframe();
    };

    const handleMessage = (event) => {
      if (event.data && event.data.type === 'getTheme') {
        sendThemeToIframe();
      }
    };

    window.addEventListener('message', handleMessage);
    iframe.addEventListener('load', onLoad);

    // Handle an already-loaded frame (e.g. a colorMode toggle re-runs this
    // effect): re-run the per-page fixups and push the new theme.
    try {
      const doc = iframe.contentDocument;
      if (doc && doc.location && doc.location.href !== 'about:blank') {
        maybeInjectCppLanding(doc);
        fixExternalLinks(doc);
      }
    } catch (e) {
      // cross-origin — ignore
    }
    sendThemeToIframe();

    return () => {
      window.removeEventListener('message', handleMessage);
      iframe.removeEventListener('load', onLoad);
      unloadCleanups.forEach((fn) => fn());
    };
  }, [colorMode]);

  return (
    <iframe
      ref={iframeRef}
      src={resolvedSrc}
      title={title}
      style={{
        border: 'none',
        minHeight: '70vh',
        height: 'calc(100vh - 120px)',
        // Match the baked theme's page background (--page-background-color in
        // static/api-embed.css: white in light, oklch(0.19 0.02 250) in dark) so
        // there is no white flash before the child's first (already-themed)
        // paint — e.g. before its HTML has been fetched.
        backgroundColor: colorMode === 'dark' ? 'oklch(0.19 0.02 250)' : '#ffffff',
        ...style,
      }}
      width="100%"
      {...props}
    />
  );
}
